// alt-frontend-sv/src/lib/components/mobile/EmptyFeedState.svelte
<script lang="ts">
import { Plus, Rss } from "@lucide/svelte";
import { Button } from "$lib/components/ui/button";
</script>

<div
	role="region"
	aria-label="Empty feed state"
	class="flex flex-col justify-center items-center min-h-[70vh] p-6 text-center"
>
	<div class="flex flex-col gap-8 max-w-[400px]">
		<!-- Animated Icon -->
		<div
			data-testid="empty-state-icon"
			class="w-[120px] h-[120px] flex items-center justify-center rounded-full border-2"
			style="background: var(--alt-glass); border-color: var(--alt-glass-border);"
		>
			<Rss size={56} style="color: var(--alt-text-secondary);" stroke-width="1.5" />
		</div>

		<!-- Heading -->
		<div class="flex flex-col gap-3">
			<h2
				class="text-2xl md:text-3xl font-bold"
				style="color: var(--alt-text-primary); background: var(--accent-gradient); -webkit-background-clip: text; -webkit-text-fill-color: transparent; background-clip: text;"
			>
				No Feeds Yet
			</h2>

			<p
				class="text-base leading-relaxed px-4"
				style="color: var(--alt-text-secondary);"
			>
				Start by adding your first RSS feed to begin reading articles from your
				favorite sources.
			</p>
		</div>

		<!-- Call to Action Button -->
		<a href="/mobile/feeds/register">
			<Button
				size="lg"
				class="rounded-2xl font-bold px-8"
				style="background: linear-gradient(to right, #FF416C, #FF4B2B); color: white;"
			>
				<div class="flex items-center gap-2">
					<Plus size={20} />
					<span>Add Your First Feed</span>
				</div>
			</Button>
		</a>
	</div>
</div>

// alt-frontend/src/components/mobile/EmptyFeedState.tsx
"use client";

import { Box, Button, Flex, Text, VStack } from "@chakra-ui/react";
import { motion } from "framer-motion";
import { Plus, Rss } from "lucide-react";
import Link from "next/link";

/**
 * EmptyFeedState component displays a user-friendly empty state
 * when there are no feeds available. It provides clear guidance
 * and a call-to-action to register the first feed.
 */
export default function EmptyFeedState() {
  return (
    <Flex
      role="region"
      aria-label="Empty feed state"
      direction="column"
      justify="center"
      align="center"
      minH="70vh"
      p={6}
      textAlign="center"
    >
      <VStack gap={8} maxW="400px">
        {/* Animated Icon */}
        <motion.div
          data-testid="empty-state-icon"
          style={{
            width: "120px",
            height: "120px",
            display: "flex",
            alignItems: "center",
            justifyContent: "center",
            background: "var(--alt-glass)",
            borderRadius: "9999px",
            border: "2px solid var(--alt-glass-border)",
          }}
          animate={{
            scale: [1, 1.05, 1],
            opacity: [0.8, 1, 0.8],
          }}
          transition={{
            duration: 3,
            repeat: Infinity,
            ease: "easeInOut",
          }}
        >
          <Rss
            size={56}
            color="var(--alt-text-secondary)"
            strokeWidth={1.5}
          />
        </motion.div>

        {/* Heading */}
        <VStack gap={3}>
          <Text
            as="h2"
            fontSize={{ base: "2xl", md: "3xl" }}
            fontWeight="bold"
            color="var(--alt-text-primary)"
            bgGradient="var(--accent-gradient)"
            bgClip="text"
          >
            No Feeds Yet
          </Text>

          <Text
            fontSize="md"
            color="var(--alt-text-secondary)"
            lineHeight="1.6"
            px={4}
          >
            Start by adding your first RSS feed to begin reading articles from
            your favorite sources.
          </Text>
        </VStack>

        {/* Call to Action Button */}
        <Link href="/mobile/feeds/register">
          <Button
            size="lg"
            borderRadius="16px"
            bgGradient="linear(to-r, #FF416C, #FF4B2B)"
            color="white"
            fontWeight="bold"
            px={8}
            _hover={{
              transform: "translateY(-2px)",
              boxShadow: "0 8px 25px rgba(255, 65, 108, 0.4)",
            }}
            _active={{
              transform: "translateY(0)",
            }}
            transition="all 0.2s cubic-bezier(0.4, 0, 0.2, 1)"
          >
            <Flex align="center" gap={2}>
              <Plus size={20} />
              <Text>Add Your First Feed</Text>
            </Flex>
          </Button>
        </Link>

        {/* Secondary helpful text */}
        <Box
          mt={4}
          p={4}
          bg="var(--alt-glass)"
          borderRadius="12px"
          border="1px solid var(--alt-glass-border)"
          w="100%"
        >
          <Text fontSize="sm" color="var(--alt-text-secondary)">
            <strong>Tip:</strong> You can find RSS feeds from your favorite
            blogs, news sites, or podcasts. Look for the RSS icon or
            &quot;/feed&quot; in the URL.
          </Text>
        </Box>
      </VStack>
    </Flex>
  );
}
