// alt-frontend/src/components/mobile/RenderFeedDetails.tsx
import { Box, HStack, Text } from "@chakra-ui/react";
import type { CSSObject } from "@emotion/react";
import { SmartContentRenderer } from "@/components/common/SmartContentRenderer";
import type {
  FeedContentOnTheFlyResponse,
  FetchArticleSummaryResponse,
} from "@/schema/feed";

const fallbackContentStyles: CSSObject = {
  "& table": {
    width: "100%",
    borderCollapse: "collapse",
  },
  "& pre": {
    whiteSpace: "pre-wrap",
    overflowX: "auto",
  },
  "& code": {
    whiteSpace: "pre-wrap",
  },
  "& blockquote": {
    borderLeft: "3px solid rgba(255, 255, 255, 0.2)",
    paddingLeft: "12px",
    marginLeft: 0,
    color: "var(--alt-text-secondary)",
  },
};

// Union type for feedDetails
type RenderFeedDetailsProps =
  | FeedContentOnTheFlyResponse
  | FetchArticleSummaryResponse;

interface RenderFeedDetailsComponentProps {
  feedDetails?: RenderFeedDetailsProps | null;
  isLoading?: boolean;
  error?: string | null;
}

const RenderFeedDetails = ({
  feedDetails,
  isLoading,
  error,
}: RenderFeedDetailsComponentProps) => {
  // Loading state
  if (isLoading) {
    return (
      <Text
        fontStyle="italic"
        color="var(--alt-text-secondary)"
        textAlign="center"
        py={8}
      >
        Loading summary...
      </Text>
    );
  }

  // Error state
  if (error) {
    return (
      <Text
        fontStyle="italic"
        color="var(--alt-text-secondary)"
        textAlign="center"
        py={8}
      >
        {error}
      </Text>
    );
  }

  // No data available
  if (!feedDetails) {
    return (
      <Text
        fontStyle="italic"
        color="var(--alt-text-secondary)"
        textAlign="center"
        py={8}
      >
        No summary available for this article
      </Text>
    );
  }

  // FetchArticleSummaryResponse (has matched_articles property) - Rich article display
  // Check this first to prioritize Inoreader summary when available
  if (
    "matched_articles" in feedDetails &&
    feedDetails.matched_articles &&
    feedDetails.matched_articles.length > 0
  ) {
    const article = feedDetails.matched_articles[0];

    return (
      <Box px={4} py={4}>
        {/* Article Metadata */}
        <Box
          mb={4}
          p={4}
          bg="rgba(255, 255, 255, 0.05)"
          borderRadius="12px"
          border="1px solid rgba(255, 255, 255, 0.1)"
        >
          <Text
            fontSize="xl"
            fontWeight="bold"
            color="var(--text-primary)"
            mb={2}
            lineHeight="1.4"
          >
            {article.title}
          </Text>

          <HStack gap={3} fontSize="md" color="var(--alt-text-secondary)">
            {article.author && <Text>By {article.author}</Text>}

            <Text>
              {new Date(article.published_at).toLocaleDateString("ja-JP", {
                year: "numeric",
                month: "short",
                day: "numeric",
              })}
            </Text>

            <Text
              px={2}
              py={1}
              bg="var(--accent-primary)"
              borderRadius="full"
              fontSize="xs"
              fontWeight="semibold"
            >
              {article.content_type}
            </Text>
          </HStack>
        </Box>

        {/* Smart Content Rendering */}
        <Box
          bg="rgba(255, 255, 255, 0.02)"
          borderRadius="8px"
          p={3}
          border="1px solid rgba(255, 255, 255, 0.05)"
        >
          <SmartContentRenderer
            content={article.content}
            contentType={article.content_type}
            className="article-content"
            maxHeight="50vh"
            showMetadata={true}
            onError={(error) => {
              console.error("Content rendering error:", error);
            }}
          />
        </Box>
      </Box>
    );
  }

  // FeedContentOnTheFlyResponse (has content property) - Simple content display
  // This is the fallback when Inoreader summary is not available
  if ("content" in feedDetails) {
    return (
      <Box px={4} py={4}>
        <Box
          color="var(--text-primary)"
          lineHeight="1.6"
          fontSize="md"
          maxW="100%"
          overflowWrap="anywhere"
          wordBreak="break-word"
          css={fallbackContentStyles}
        >
          {/* content is already sanitized server-side as SafeHtmlString */}
          <Box
            as="div"
            display="block"
            width="100%"
            wordBreak="break-word"
            overflowWrap="anywhere"
            dangerouslySetInnerHTML={{
              __html: feedDetails.content, // SafeHtmlString - already sanitized
            }}
          />
        </Box>
      </Box>
    );
  }

  // No data available
  return (
    <Text
      fontStyle="italic"
      color="var(--alt-text-secondary)"
      textAlign="center"
      py={8}
    >
      No summary available for this article
    </Text>
  );
};

export default RenderFeedDetails;

// alt-frontend-sv/src/lib/components/mobile/RenderFeedDetails.svelte
<script lang="ts">
import type {
	FeedContentOnTheFlyResponse,
	FetchArticleSummaryResponse,
} from "$lib/api/client";

interface Props {
	feedDetails?:
		| FetchArticleSummaryResponse
		| FeedContentOnTheFlyResponse
		| null;
	isLoading?: boolean;
	error?: string | null;
}

const { feedDetails, isLoading = false, error = null }: Props = $props();
</script>

{#if isLoading}
	<p
		class="text-center py-8 italic"
		style="color: var(--text-secondary);"
	>
		Loading summary...
	</p>
{:else if error}
	<p
		class="text-center py-8 italic"
		style="color: var(--text-secondary);"
	>
		{error}
	</p>
{:else if !feedDetails}
	<p
		class="text-center py-8 italic"
		style="color: var(--text-secondary);"
	>
		No summary available for this article
	</p>
{:else if "matched_articles" in feedDetails && feedDetails.matched_articles?.length > 0}
	<!-- FetchArticleSummaryResponse - Rich article display -->
	{@const article = feedDetails.matched_articles[0]}
	<div class="px-4 py-4">
		<!-- Article Metadata -->
		<div
			class="mb-4 p-4 rounded-xl border"
			style="
				background: rgba(255, 255, 255, 0.05);
				border-color: rgba(255, 255, 255, 0.1);
			"
		>
			<h2
				class="text-xl font-bold mb-2 leading-tight"
				style="color: var(--text-primary);"
			>
				{article.title}
			</h2>

			<div class="flex items-center gap-3 text-base" style="color: var(--text-secondary);">
				{#if article.author}
					<p>By {article.author}</p>
				{/if}

				<p>
					{new Date(article.published_at).toLocaleDateString("ja-JP", {
						year: "numeric",
						month: "short",
						day: "numeric",
					})}
				</p>

				<span
					class="px-2 py-1 rounded-full text-xs font-semibold"
					style="background: var(--accent-primary);"
				>
					{article.content_type}
				</span>
			</div>
		</div>

		<!-- Content -->
		<div
			class="rounded-lg p-3 border"
			style="
				background: rgba(255, 255, 255, 0.02);
				border-color: rgba(255, 255, 255, 0.05);
			"
		>
			<div
				class="article-content max-h-[50vh] overflow-auto"
				style="color: var(--text-primary); line-height: 1.7;"
			>
				{@html article.content}
			</div>
		</div>
	</div>
{:else if "content" in feedDetails && feedDetails.content}
	<!-- FeedContentOnTheFlyResponse - Simple content display -->
	<div class="px-4 py-4">
		<div
			class="text-base leading-relaxed break-words"
			style="color: var(--text-primary);"
		>
			{@html feedDetails.content}
		</div>
	</div>
{:else}
	<p
		class="text-center py-8 italic"
		style="color: var(--text-secondary);"
	>
		No summary available for this article
	</p>
{/if}

<style>
	:global(.article-content) {
		word-break: break-word;
		overflow-wrap: anywhere;
	}

	:global(.article-content p) {
		margin-bottom: 1em;
		line-height: 1.7;
	}

	:global(.article-content h1),
	:global(.article-content h2),
	:global(.article-content h3),
	:global(.article-content h4),
	:global(.article-content h5),
	:global(.article-content h6) {
		margin-top: 1.5em;
		margin-bottom: 0.5em;
		font-weight: bold;
		color: var(--text-primary);
	}

	:global(.article-content h1) {
		font-size: 1.5em;
	}

	:global(.article-content h2) {
		font-size: 1.3em;
	}

	:global(.article-content h3) {
		font-size: 1.1em;
	}

	:global(.article-content ul),
	:global(.article-content ol) {
		margin-left: 1.5em;
		margin-bottom: 1em;
	}

	:global(.article-content li) {
		margin-bottom: 0.3em;
	}

	:global(.article-content a) {
		color: var(--accent-primary);
		text-decoration: underline;
	}

	:global(.article-content a:hover) {
		color: var(--accent-secondary);
	}

	:global(.article-content img) {
		max-width: 100%;
		height: auto;
		border-radius: 8px;
		margin-top: 1em;
		margin-bottom: 1em;
	}

	:global(.article-content blockquote) {
		border-left: 3px solid var(--accent-primary);
		padding-left: 1em;
		margin-left: 0;
		font-style: italic;
		background: rgba(255, 255, 255, 0.05);
		padding: 1em;
		border-radius: 0 8px 8px 0;
	}

	:global(.article-content pre) {
		background: rgba(0, 0, 0, 0.3);
		padding: 1em;
		border-radius: 8px;
		overflow: auto;
		font-size: 0.9em;
	}

	:global(.article-content code) {
		background: rgba(0, 0, 0, 0.2);
		padding: 0.2em 0.4em;
		border-radius: 3px;
		font-size: 0.9em;
		font-family: monospace;
	}

	:global(.article-content table) {
		border-collapse: collapse;
		width: 100%;
		margin-top: 1em;
		margin-bottom: 1em;
	}

	:global(.article-content th),
	:global(.article-content td) {
		border: 1px solid rgba(255, 255, 255, 0.2);
		padding: 0.5em;
		text-align: left;
	}

	:global(.article-content th) {
		background: rgba(255, 255, 255, 0.1);
		font-weight: bold;
	}

	:global(.article-content::-webkit-scrollbar) {
		width: 4px;
	}

	:global(.article-content::-webkit-scrollbar-track) {
		background: transparent;
		border-radius: 2px;
	}

	:global(.article-content::-webkit-scrollbar-thumb) {
		background: rgba(255, 255, 255, 0.2);
		border-radius: 2px;
	}

	:global(.article-content::-webkit-scrollbar-thumb:hover) {
		background: rgba(255, 255, 255, 0.3);
	}
</style>
