// alt-frontend/app/src/components/mobile/VirtualFeedList.tsx
"use client";

import { Flex } from '@chakra-ui/react';
import { Feed } from '@/schema/feed';
import FeedCard from './FeedCard';

interface VirtualFeedListProps {
  /**
   * Feed items that should be rendered (already filtered for read status).
   */
  feeds: Feed[];
  readFeeds: Set<string>;
  onMarkAsRead: (feedLink: string) => void;
}

export const VirtualFeedList: React.FC<VirtualFeedListProps> = ({
  feeds,
  readFeeds,
  onMarkAsRead,
}) => {
  if (feeds.length === 0) {
    return null;
  }

  return (
    <Flex direction="column" gap={4} data-testid="virtual-feed-list">
      {feeds.map((feed: Feed, index: number) => (
        <div key={feed.link} data-testid={`virtual-feed-item-${index}`}>
          <FeedCard
            feed={feed}
            isReadStatus={readFeeds.has(feed.link)}
            setIsReadStatus={() => onMarkAsRead(feed.link)}
          />
        </div>
      ))}
    </Flex>
  );
};

export default VirtualFeedList;

// alt-frontend-sv/src/lib/components/mobile/VirtualFeedList.svelte
<script lang="ts">
import type { RenderFeed } from "#lib/schema/feed.js";
import FeedCard from "./FeedCard.svelte";

interface Props {
	feeds: RenderFeed[];
	readFeeds: Set<string>;
	onMarkAsRead: (feedLink: string) => void;
}

const { feeds, readFeeds, onMarkAsRead }: Props = $props();
</script>

{#if feeds.length === 0}
	<!-- Empty state -->
{:else}
<div
	class="flex flex-col gap-4 mt-2"
	data-testid="virtual-feed-list"
	style="content-visibility: auto; contain-intrinsic-size: 800px;"
>
	{#each feeds as feed, index (feed.link)}
		<div data-testid="virtual-feed-item-{index}">
			<FeedCard
				{feed}
				isReadStatus={readFeeds.has(feed.normalizedUrl)}
				setIsReadStatus={(feedLink: string) => onMarkAsRead(feedLink)}
			/>
		</div>
	{/each}
</div>
{/if}
