// alt-frontend/app/src/components/mobile/utils/FloatingMenu.tsx
"use client";

import {
  Box,
  Button,
  Text,
  VStack,
  HStack,
  Drawer,
  Portal,
  Flex,
} from "@chakra-ui/react";
import {
  Accordion,
  AccordionItem,
  AccordionButton,
  AccordionPanel,
  AccordionIcon,
} from "@chakra-ui/accordion";
import Link from "next/link";
import { usePathname } from "next/navigation";
import { useState, useCallback, useEffect } from "react";
import { Rss, Search, Plus, Eye, ChartBar, Home, Newspaper, Star, Menu, X } from "lucide-react";
import { ThemeToggle } from "../../ThemeToggle";

type MenuCategory = "feeds" | "other" | "articles";

interface MenuItem {
  label: string;
  href: string;
  category: MenuCategory;
  icon: React.ReactNode;
  description?: string;
}

export const FloatingMenu = () => {
  const [isOpen, setIsOpen] = useState(false);
  const [isPrefetched, setIsPrefetched] = useState(false);
  const pathname = usePathname();

  const handleCloseMenu = useCallback(() => {
    setIsOpen(false);
  }, []);

  // Handle keyboard interactions
  useEffect(() => {
    const handleKeyDown = (event: KeyboardEvent) => {
      if (event.key === "Escape" && isOpen) {
        handleCloseMenu();
      }
    };

    if (isOpen) {
      document.addEventListener("keydown", handleKeyDown);
      // Prevent background scrolling when menu is open
      document.body.style.overflow = "hidden";

      // Focus management for accessibility
      setTimeout(() => {
        const firstAccordionButton = document.querySelector(
          '[data-testid="tab-feeds"]',
        ) as HTMLElement;
        if (firstAccordionButton) {
          firstAccordionButton.focus();
        }
      }, 100);
    } else {
      document.body.style.overflow = "unset";
    }

    return () => {
      document.removeEventListener("keydown", handleKeyDown);
      document.body.style.overflow = "unset";
    };
  }, [isOpen, handleCloseMenu]);

  useEffect(() => {
    if (isPrefetched) return;

    const prefetch = () => setIsPrefetched(true);
    if (typeof window !== "undefined" && "requestIdleCallback" in window) {
      (window as Window).requestIdleCallback(prefetch);
    } else {
      // Fallback for environments without requestIdleCallback
      setTimeout(prefetch, 0);
    }
  }, [isPrefetched]);

  const menuItems: MenuItem[] = [
    {
      label: "View Feeds",
      href: "/mobile/feeds",
      category: "feeds",
      icon: <Rss size={18} />,
      description: "Browse all RSS feeds",
    },
    {
      label: "Viewed Feeds",
      href: "/mobile/feeds/viewed",
      category: "feeds",
      icon: <Eye size={18} />,
      description: "Previously read feeds",
    },
    {
      label: "Register Feed",
      href: "/mobile/feeds/register",
      category: "feeds",
      icon: <Plus size={18} />,
      description: "Add new RSS feed",
    },
    {
      label: "Search Feeds",
      href: "/mobile/feeds/search",
      category: "feeds",
      icon: <Search size={18} />,
      description: "Find specific feeds",
    },
    {
      label: "Search Articles",
      href: "/mobile/articles/search",
      category: "articles",
      icon: <Newspaper size={18} />,
      description: "Search through articles",
    },
    {
      label: "View Stats",
      href: "/mobile/feeds/stats",
      category: "other",
      icon: <ChartBar size={18} />,
      description: "Analytics & insights",
    },
    {
      label: "Home",
      href: "/",
      category: "other",
      icon: <Home size={18} />,
      description: "Return to dashboard",
    },
  ];

  // Helper that closes menu when a link is activated
  const handleNavigate = useCallback(() => {
    handleCloseMenu();
  }, [handleCloseMenu]);

  // Helper to check if a menu item is active
  const isActiveMenuItem = useCallback(
    (href: string): boolean => {
      return pathname === href;
    },
    [pathname],
  );

  // Group menu items into categories for accordion UI
  const categories = [
    {
      title: "Feeds",
      items: menuItems.filter((i) => i.category === "feeds"),
      icon: <Rss size={16} />,
      gradient: "var(--app-bg)",
    },
    {
      title: "Articles",
      items: menuItems.filter((i) => i.category === "articles"),
      icon: <Newspaper size={16} />,
      gradient: "var(--accent-gradient)",
    },
    {
      title: "Other",
      items: menuItems.filter((i) => i.category === "other"),
      icon: <Star size={16} />,
      gradient: "var(--accent-gradient)",
    },
  ];

  return (
    <>
      <Drawer.Root
        open={isOpen}
        onOpenChange={(e) => setIsOpen(e.open)}
        placement="bottom"
      >
        <Drawer.Trigger asChild>
          <Box position="fixed" bottom={6} right={6} zIndex={1000}>
            <Button
              data-testid="floating-menu-button"
              size="md"
              borderRadius="full"
              bg="var(--alt-primary)"
              color="var(--text-primary)"
              p={0}
              w="48px"
              h="48px"
              border="2px solid rgba(255, 255, 255, 0.2)"
              _hover={{
                transform: "scale(1.05) rotate(90deg)",
                shadow: "0 6px 20px var(--alt-primary)",
                bg: "var(--alt-primary)",
              }}
              _active={{
                transform: "scale(0.95) rotate(90deg)",
              }}
              transition="all 0.3s cubic-bezier(0.4, 0, 0.2, 1)"
              tabIndex={0}
              role="button"
              aria-label="Open floating menu"
              position="relative"
              overflow="hidden"
              onClick={() => setIsOpen(true)}
            >
              {/* Animated background pulse */}
              <Box
                position="absolute"
                top="50%"
                left="50%"
                transform="translate(-50%, -50%)"
                w="120%"
                h="120%"
                bg="var(--alt-primary)"
                borderRadius="full"
                opacity="0.3"
                css={{
                  "@keyframes pulse": {
                    "0%, 100%": {
                      opacity: 0.6,
                      transform: "translate(-50%, -50%) scale(1)",
                    },
                    "50%": {
                      opacity: 0.8,
                      transform: "translate(-50%, -50%) scale(1.1)",
                    },
                  },
                  animation: "pulse 2s ease-in-out infinite",
                }}
              />
              <Menu size={16} style={{ position: "relative", zIndex: 1 }} />
            </Button>
          </Box>
        </Drawer.Trigger>

        <Portal>
          <Drawer.Backdrop
            data-testid="modal-backdrop"
            bg="rgba(0, 0, 0, 0.7)"
            backdropFilter="blur(12px)"
          />
          <Drawer.Positioner>
            <Drawer.Content
              w="100vw"
              maxW="100vw"
              bg="var(--app-bg)"
              color="white"
              borderTopRadius="32px"
              pt={6}
              data-testid="bottom-sheet-menu"
              minH="70vh"
              maxH="90vh"
              overflowY="auto"
              position="relative"
              _before={{
                content: '""',
                position: "absolute",
                top: 0,
                left: 0,
                right: 0,
                height: "4px",
                bgGradient: "var(--accent-gradient)",
                borderTopRadius: "32px",
              }}
            >
              {/* Drag handle */}
              <Box
                w="48px"
                h="4px"
                bg="rgba(255, 255, 255, 0.3)"
                borderRadius="full"
                mx="auto"
                mb={4}
              />

              <Drawer.Header
                borderBottomWidth="1px"
                borderColor="rgba(255, 255, 255, 0.1)"
                pb={4}
                px={6}
              >
                <Flex align="center" justify="space-between">
                  <HStack gap={3}>
                    <Box
                      w="40px"
                      h="40px"
                      bg="var(--alt-primary)"
                      borderRadius="full"
                      display="flex"
                      alignItems="center"
                      justifyContent="center"
                    >
                      <Star size={18} color="white" />
                    </Box>
                    <Box>
                      <Drawer.Title
                        fontSize="xl"
                        fontWeight="bold"
                        bgGradient="var(--accent-primary)"
                        bgClip="text"
                      >
                        Navigation
                      </Drawer.Title>
                      <Text fontSize="sm" color="var(--text-primary)">
                        Quick access to all features
                      </Text>
                    </Box>
                  </HStack>
                </Flex>
              </Drawer.Header>

              <Drawer.Body px={6} py={4}>
                <Accordion allowToggle defaultIndex={0}>
                  {categories.map((cat, idx) => (
                    <AccordionItem key={idx} border="none" mb={4}>
                      {({ isExpanded }) => (
                        <>
                          <h2>
                            <AccordionButton
                              data-testid={`tab-${cat.title.toLowerCase()}`}
                              px={6}
                              py={5}
                              justifyContent="space-between"
                              bg="var(--alt-glass)"
                              backdropFilter="blur(20px)"
                              border="1px solid var(--alt-glass-border)"
                              borderRadius="16px"
                              _hover={{
                                bg: "var(--alt-glass)",
                                transform: "translateY(-2px)",
                                boxShadow: "0 8px 25px rgba(0, 0, 0, 0.2)",
                              }}
                              _expanded={{
                                bg: "var(--alt-glass)",
                                borderColor: "var(--alt-glass-border)",
                                boxShadow: "0 0 30px var(--alt-glass-shadow)",
                              }}
                              transition="all 0.3s cubic-bezier(0.4, 0, 0.2, 1)"
                            >
                              <HStack gap={4} flex="1">
                                <Box
                                  w="32px"
                                  h="32px"
                                  bg="var(--alt-secondary)"
                                  borderRadius="8px"
                                  display="flex"
                                  alignItems="center"
                                  justifyContent="center"
                                  color="white"
                                >
                                  {cat.icon}
                                </Box>
                                <Box textAlign="left">
                                  <Text
                                    fontWeight="bold"
                                    fontSize="lg"
                                    color="var(--text-primary)"
                                  >
                                    {cat.title}
                                  </Text>
                                  <Text
                                    fontSize="sm"
                                    color="var(--text-primary)"
                                  >
                                    {cat.items.length} items
                                  </Text>
                                </Box>
                              </HStack>
                              <AccordionIcon
                                color="var(--text-primary)"
                                transition="transform 0.2s"
                                transform={isExpanded ? "rotate(180deg)" : "rotate(0deg)"}
                              />
                            </AccordionButton>
                          </h2>
                          <AccordionPanel pb={4} pt={4} px={0}>
                            <VStack gap={2} align="stretch">
                              {cat.items.map((item, i) => {
                                const isActive = isActiveMenuItem(item.href);
                                return (
                                  <Link
                                    key={i}
                                    href={item.href}
                                    style={{ textDecoration: "none" }}
                                    onClick={handleNavigate}
                                  >
                                    <Box
                                      mx="auto"
                                      maxW="320px"
                                      w="85%"
                                      bg={
                                        isActive
                                          ? "var(--alt-glass)"
                                          : "var(--alt-glass)"
                                      }
                                      borderRadius="10px"
                                      border={`1px solid ${isActive
                                        ? "var(--alt-glass-border)"
                                        : "var(--alt-glass-border)"
                                        }`}
                                      p={3}
                                      _hover={{
                                        bg: isActive
                                          ? "var(--alt-glass)"
                                          : "var(--alt-glass)",
                                        borderColor: "var(--alt-glass-border)",
                                        transform: "translateY(-1px)",
                                        boxShadow:
                                          "0 2px 8px var(--alt-glass-shadow)",
                                      }}
                                      _active={{ transform: "translateY(0px)" }}
                                      transition="all 0.2s ease"
                                      position="relative"
                                      overflow="hidden"
                                    >
                                      {/* Active indicator */}
                                      {isActive && (
                                        <Box
                                          position="absolute"
                                          left="0"
                                          top="0"
                                          bottom="0"
                                          w="3px"
                                          bg="var(--accent-gradient)"
                                          borderRadius="0 2px 2px 0"
                                        />
                                      )}

                                      <HStack gap={3} align="center">
                                        <Box
                                          color={
                                            isActive
                                              ? "var(--accent-primary)"
                                              : "var(--alt-text-secondary)"
                                          }
                                          transition="color 0.2s ease"
                                          fontSize="16px"
                                        >
                                          {item.icon}
                                        </Box>
                                        <Box flex="1">
                                          <HStack
                                            justify="space-between"
                                            align="center"
                                          >
                                            <Text
                                              color={
                                                isActive ? "var(--text-primary)" : "var(--alt-secondary)"
                                              }
                                              fontWeight={
                                                isActive ? "semibold" : "medium"
                                              }
                                              fontSize="sm"
                                              lineHeight="1.2"
                                            >
                                              {item.label}
                                            </Text>
                                          </HStack>
                                          {item.description && (
                                            <Text
                                              fontSize="xs"
                                              color="var(--text-primary)"
                                              mt={0.5}
                                            >
                                              {item.description}
                                            </Text>
                                          )}
                                        </Box>
                                      </HStack>
                                    </Box>
                                  </Link>
                                );
                              })}
                            </VStack>
                          </AccordionPanel>
                        </>
                      )}
                    </AccordionItem>
                  ))}
                </Accordion>

                {/* Theme Toggle */}
                <Box
                  mt={6}
                  pt={4}
                  borderTop="1px solid var(--accent-primary)"
                >
                  <ThemeToggle size="md" showLabel />
                </Box>
              </Drawer.Body>

              <Drawer.CloseTrigger asChild>
                <Button
                  aria-label="Close menu"
                  data-testid="close-menu-button"
                  bg="var(--alt-primary)"
                  color="var(--text-primary)"
                  borderRadius="full"
                  _hover={{
                    bg: "var(--accent-primary)",
                    transform: "rotate(90deg)",
                  }}
                  position="absolute"
                  top="20px"
                  right="20px"
                  w="40px"
                  h="40px"
                  transition="all 0.2s ease"
                >
                  <X size={18} />
                </Button>
              </Drawer.CloseTrigger>
            </Drawer.Content>
          </Drawer.Positioner>
        </Portal>
      </Drawer.Root>

      {/* Hidden pre-rendered menu to warm up rendering & reduce first-open cost */}
      {!isOpen && isPrefetched && (
        <Box display="none">
          {menuItems.map((item) => (
            <Link key={item.href} href={item.href}>
              {item.label}
            </Link>
          ))}
        </Box>
      )}
    </>
  );
};

// alt-frontend-sv/src/lib/components/mobile/feeds/swipe/FloatingMenu.svelte
<script lang="ts">
	import {
		CalendarRange,
		ChartBar,
		Eye,
		Globe,
		Home,
		Infinity as InfinityIcon,
		Link as LinkIcon,
		Menu,
		Newspaper,
		Plus,
		Rss,
		Search,
		Star,
		X,
	} from "@lucide/svelte";
	import { onMount } from "svelte";
	import { browser } from "$app/environment";
	import { page } from "$app/state";
	import * as Accordion from "$lib/components/ui/accordion";
	import { Button } from "$lib/components/ui/button";
	import * as Dialog from "$lib/components/ui/dialog";

	let isOpen = $state(false);
	let isPrefetched = $state(false);

	// Prevent body scroll lock when dialog is closed
	$effect(() => {
		if (!browser) return;
		if (!isOpen) {
			// Ensure body scroll is enabled when dialog is closed
			document.body.style.overflow = "";
		}
	});

	const svBasePath = "/sv";

	const menuItems = [
		{
			label: "View Feeds",
			href: `${svBasePath}/mobile/feeds`,
			category: "feeds",
			icon: Rss,
			description: "Browse all RSS feeds",
		},
		{
			label: "Swipe Mode",
			href: `${svBasePath}/mobile/feeds/swipe`,
			category: "feeds",
			icon: InfinityIcon,
			description: "Swipe through feeds",
		},
		{
			label: "Viewed Feeds",
			href: `${svBasePath}/mobile/feeds/viewed`,
			category: "feeds",
			icon: Eye,
			description: "Previously read feeds",
		},
		{
			label: "Favorite Feeds",
			href: `${svBasePath}/mobile/feeds/favorites`,
			category: "feeds",
			icon: Star,
			description: "Favorited articles",
		},
		{
			label: "Register Feed",
			href: `${svBasePath}/mobile/feeds/register`,
			category: "feeds",
			icon: Plus,
			description: "Add new RSS feed",
		},
		{
			label: "Manage Feeds Links",
			href: `${svBasePath}/mobile/feeds/manage`,
			category: "feeds",
			icon: LinkIcon,
			description: "Add or remove your registered RSS sources",
		},
		{
			label: "Search Feeds",
			href: `${svBasePath}/mobile/feeds/search`,
			category: "feeds",
			icon: Search,
			description: "Find specific feeds",
		},
		{
			label: "7-Day Recap",
			href: `${svBasePath}/mobile/recap/7days`,
			category: "recap",
			icon: CalendarRange,
			description: "Review the weekly highlights",
		},
		{
			label: "Morning Letter",
			href: `${svBasePath}/mobile/recap/morning-letter/updates`,
			category: "recap",
			icon: Newspaper,
			description: "Today's overnight updates",
		},
		{
			label: "View Articles",
			href: `${svBasePath}/mobile/articles/view`,
			category: "articles",
			icon: Newspaper,
			description: "Browse all articles",
		},
		{
			label: "Search Articles",
			href: `${svBasePath}/mobile/articles/search`,
			category: "articles",
			icon: Search,
			description: "Search through articles",
		},
		{
			label: "View Stats",
			href: `${svBasePath}/mobile/feeds/stats`,
			category: "other",
			icon: ChartBar,
			description: "Analytics & insights",
		},
		{
			label: "Home",
			href: `${svBasePath}/`,
			category: "other",
			icon: Home,
			description: "Return to dashboard",
		},
		{
			label: "Manage Domains",
			href: `${svBasePath}/admin/scraping-domains`,
			category: "other",
			icon: Globe,
			description: "Manage scraping domains",
		},
	];

	const categories = [
		{
			title: "Feeds",
			items: menuItems.filter((i) => i.category === "feeds"),
			icon: Rss,
		},
		{
			title: "Recap",
			items: menuItems.filter((i) => i.category === "recap"),
			icon: CalendarRange,
		},
		{
			title: "Articles",
			items: menuItems.filter((i) => i.category === "articles"),
			icon: Newspaper,
		},
		{
			title: "Other",
			items: menuItems.filter((i) => i.category === "other"),
			icon: Star,
		},
	];

	function handleNavigate() {
		isOpen = false;
	}

	function isActiveMenuItem(href: string): boolean {
		return page.url.pathname === href;
	}

	onMount(() => {
		if (isPrefetched) return;

		const prefetch = () => {
			isPrefetched = true;
		};

		if ("requestIdleCallback" in window) {
			window.requestIdleCallback(prefetch);
		} else {
			setTimeout(prefetch, 0);
		}
	});
</script>

<Dialog.Root bind:open={isOpen}>
	{#if !isOpen}
		<div
			class="fixed bottom-6 right-6 z-[1000] pb-[calc(1.5rem+env(safe-area-inset-bottom,0px))] pointer-events-auto"
		>
			<Dialog.Trigger
				class="h-12 w-12 rounded-full border-2 border-[var(--text-primary)] bg-[var(--bg-surface)] text-[var(--text-primary)] shadow-[var(--shadow-glass)] backdrop-blur-md transition-all duration-300 hover:scale-105 hover:rotate-90 hover:bg-[var(--bg-surface-hover)] hover:border-[var(--accent-primary)] active:scale-95 active:rotate-90 inline-flex shrink-0 items-center justify-center focus-visible:outline-none outline-none disabled:pointer-events-none disabled:opacity-60"
				aria-label="Open floating menu"
			>
				<Menu class="h-5 w-5 relative z-[1]" />
			</Dialog.Trigger>
		</div>
	{/if}
	<Dialog.Content
		showCloseButton={false}
		class="max-h-[90vh] min-h-[70vh] rounded-t-[32px] border-t border-[var(--border-glass)] text-[var(--text-primary)] shadow-[0_-10px_40px_rgba(0,0,0,0.2)] backdrop-blur-[20px] !fixed !bottom-0 !left-0 !right-0 !top-auto !translate-x-0 !translate-y-0 !start-auto w-full max-w-full sm:max-w-full p-0 gap-0 flex flex-col overflow-hidden"
		style="background: var(--app-bg);"
	>
		<Dialog.Header class="border-b border-[var(--border-glass)] px-6 pb-6">
			<div class="flex items-center justify-between">
				<div class="flex gap-3">
					<div
						class="flex h-10 w-10 items-center justify-center rounded-xl border border-[var(--border-glass)] bg-[var(--bg-surface)]"
					>
						<Star class="h-5 w-5 text-[var(--accent-primary)]" />
					</div>
					<div class="text-left">
						<Dialog.Title class="text-xl font-bold text-[var(--text-primary)]">
							Navigation
						</Dialog.Title>
						<Dialog.Description class="text-sm text-[var(--text-secondary)]">
							Quick access to all features
						</Dialog.Description>
					</div>
				</div>
			</div>
		</Dialog.Header>
		<div
			class="overflow-y-auto px-6 py-6 pb-[calc(1.5rem+env(safe-area-inset-bottom,0px))]"
		>
			<Accordion.Root type="multiple" class="w-full" value={["item-0"]}>
				{#each categories as cat, idx}
					<Accordion.Item value={`item-${idx}`} class="mb-4 border-none">
						<Accordion.Trigger
							class="flex w-full items-center justify-between rounded-2xl px-4 py-4 hover:bg-[var(--bg-surface-hover)] hover:no-underline data-[state=open]:bg-[var(--bg-surface)] transition-all duration-200"
						>
							<div class="flex items-center gap-4">
								<div
									class="text-[var(--text-secondary)] group-data-[state=open]:text-[var(--accent-primary)] transition-colors duration-200"
								>
									<cat.icon class="h-4 w-4" />
								</div>
								<span class="text-lg font-semibold text-[var(--text-primary)]">
									{cat.title}
								</span>
							</div>
						</Accordion.Trigger>
						<Accordion.Content class="pt-2 px-2 pb-2">
							<div class="flex flex-col gap-1">
								{#each cat.items as item}
									{@const active = isActiveMenuItem(item.href)}
									<a
										href={item.href}
										onclick={handleNavigate}
										class="block rounded-xl p-3 transition-all duration-200 hover:bg-[var(--bg-surface-hover)] {active
											? 'bg-[var(--bg-surface-active)]'
											: 'bg-transparent'}"
									>
										<div class="flex items-center gap-3">
											<div
												class={active
													? "text-[var(--accent-primary)]"
													: "text-[var(--text-secondary)]"}
											>
												<item.icon class="h-4 w-4" />
											</div>
											<div class="flex-1">
												<div
													class="text-sm font-medium {active
														? 'text-[var(--text-primary)] font-semibold'
														: 'text-[var(--text-primary)]'}"
												>
													{item.label}
												</div>
												{#if item.description}
													<div
														class="mt-0.5 text-xs text-[var(--text-secondary)]"
													>
														{item.description}
													</div>
												{/if}
											</div>
										</div>
									</a>
								{/each}
							</div>
						</Accordion.Content>
					</Accordion.Item>
				{/each}
			</Accordion.Root>
		</div>
		<Dialog.Close
			class="absolute right-6 top-6 h-10 w-10 rounded-full border-2 border-transparent bg-transparent text-[var(--text-primary)] hover:bg-[var(--bg-surface-hover)] hover:border-[var(--surface-border)] hover:rotate-90 hover:border-[var(--accent-primary)] transition-all duration-200 inline-flex shrink-0 items-center justify-center focus-visible:outline-none outline-none disabled:pointer-events-none disabled:opacity-60 border border-[var(--border-glass)] bg-[var(--bg-glass)] backdrop-blur-md"
			aria-label="Close dialog"
		>
			<X class="h-4 w-4" />
		</Dialog.Close>
	</Dialog.Content>
</Dialog.Root>
