// alt-frontend/src/components/mobile/feeds/swipe/SwipeFeedCard.tsx
"use client";

import {
  Box,
  Button,
  Flex,
  HStack,
  Link,
  Spinner,
  Text,
  VStack,
} from "@chakra-ui/react";
import type { CSSObject } from "@emotion/react";
import { animated, useSpring, useTransition } from "@react-spring/web";
import { useDrag } from "@use-gesture/react";
import {
  Archive,
  BookOpen,
  BotMessageSquare,
  Sparkles,
  SquareArrowOutUpRight,
} from "lucide-react";
import { memo, useCallback, useEffect, useMemo, useRef, useState } from "react";
import { articleApi } from "@/lib/api";
import type { SafeHtmlString } from "@/lib/server/sanitize-html";
import type { RenderFeed } from "@/schema/feed";
import { renderingRegistry } from "@/utils/renderingStrategies";

const SWIPE_DISTANCE = 80;
const SWIPE_VELOCITY = 0.5;
const _DISMISS_DELAY = 140;

const scrollAreaStyles: CSSObject = {
  "&::-webkit-scrollbar": {
    width: "4px",
  },
  "&::-webkit-scrollbar-track": {
    background: "transparent",
    borderRadius: "2px",
  },
  "&::-webkit-scrollbar-thumb": {
    background: "rgba(255, 255, 255, 0.2)",
    borderRadius: "2px",
  },
  "&::-webkit-scrollbar-thumb:hover": {
    background: "rgba(255, 255, 255, 0.3)",
  },
};

type SwipeFeedCardProps = {
  feed: RenderFeed;
  statusMessage: string | null;
  onDismiss: (direction: number) => Promise<void> | void;
  getCachedContent?: (feedUrl: string) => string | null;
  isBusy?: boolean;
  initialArticleContent?: SafeHtmlString;
};

const buildContentStyles = (): CSSObject => ({
  "& img": {
    maxWidth: "100%",
    height: "auto",
    borderRadius: "8px",
    marginBottom: "0.75rem",
  },
  "& h1, & h2, & h3, & h4, & h5, & h6": {
    fontWeight: "bold",
    marginTop: "0.75rem",
    marginBottom: "0.5rem",
  },
  "& p": {
    marginBottom: "0.5rem",
    lineHeight: 1.7,
  },
  "& ul, & ol": {
    marginLeft: "1.25rem",
    marginBottom: "0.75rem",
  },
});

const normalizeDirection = (direction: number) => {
  if (!direction) {
    return 1;
  }
  return direction;
};

// Inner component that handles the drag logic and content state
const CardView = memo(
  ({
    feed,
    statusMessage,
    onDismiss,
    getCachedContent,
    isBusy = false,
    style,
    initialArticleContent,
  }: SwipeFeedCardProps & { style: any }) => {
    const [isSummaryExpanded, setIsSummaryExpanded] = useState(false);
    const [summary, setSummary] = useState<string | null>(null);
    const [isLoadingSummary, setIsLoadingSummary] = useState(false);
    const [summaryError, setSummaryError] = useState<string | null>(null);
    const [isSummarizing, setIsSummarizing] = useState(false);

    const [isContentExpanded, setIsContentExpanded] = useState(false);
    // Initialize with server-fetched content if available
    const [fullContent, setFullContent] = useState<string | null>(
      initialArticleContent ?? null,
    );
    const [isLoadingContent, setIsLoadingContent] = useState(false);
    const [contentError, setContentError] = useState<string | null>(null);

    const [isArchiving, setIsArchiving] = useState(false);
    const [isArchived, setIsArchived] = useState(false);

    const [{ x }, api] = useSpring(() => ({ x: 0 }));
    const animationInFlightRef = useRef(false);

    const sanitizedFullContent = useMemo(() => {
      if (!fullContent) {
        return null;
      }

      return renderingRegistry.render(fullContent, undefined, feed.link);
    }, [feed.link, fullContent]);

    // Auto-fetch article content when card is mounted or feed changes
    useEffect(() => {
      // Skip if content is already loaded (from initialArticleContent or previous fetch)
      if (fullContent) {
        return;
      }

      // Skip if we have initialArticleContent (already set in useState initializer)
      if (initialArticleContent) {
        return;
      }

      // Check cache first if getCachedContent is available
      const cachedContent = getCachedContent?.(feed.link);

      if (cachedContent) {
        // Use cached content instantly
        setFullContent(cachedContent);
        return;
      }

      // Cache miss - fetch in background
      // Don't set loading state to avoid UI flicker
      let isCancelled = false;

      const fetchContent = async () => {
        try {
          const contentResponse = await articleApi.getFeedContentOnTheFly({
            feed_url: feed.link,
          });

          if (isCancelled) {
            return;
          }

          if (contentResponse.content) {
            setFullContent(contentResponse.content);
            // Archive article in background (non-blocking)
            articleApi
              .archiveContent(feed.link, feed.title)
              .catch((err) =>
                console.warn("Failed to auto-archive article:", err),
              );
          }
        } catch (error) {
          // Only log error, don't update UI state
          // User can still click the button to retry
          if (!isCancelled) {
            console.error(
              "[SwipeFeedCard] Error auto-fetching content:",
              error,
            );
          }
        }
      };

      void fetchContent();

      return () => {
        isCancelled = true;
      };
    }, [
      feed.link,
      feed.title,
      fullContent,
      getCachedContent,
      initialArticleContent,
    ]);

    const resetPosition = useCallback(() => {
      api.start({
        x: 0,
        config: { tension: 250, friction: 25 },
      });
    }, [api]);

    const playDismissAnimation = useCallback(
      async (direction: number) => {
        if (animationInFlightRef.current) {
          return;
        }

        animationInFlightRef.current = true;
        const width =
          typeof window !== "undefined" && window.innerWidth
            ? window.innerWidth
            : 480;

        return new Promise<void>((resolve) => {
          api.start({
            x: direction * width * 1.2,
            config: { tension: 450, friction: 25 },
            onRest: () => {
              animationInFlightRef.current = false;
              resolve();
            },
          });
        });
      },
      [api],
    );

    const handleToggleContent = useCallback(async () => {
      if (!isContentExpanded && !fullContent) {
        // Check cache first if getCachedContent is available
        const cachedContent = getCachedContent?.(feed.link);

        if (cachedContent) {
          // Use cached content instantly
          setFullContent(cachedContent);
          setIsContentExpanded(true);
          return;
        }

        // Cache miss or no cache available - fetch normally
        setIsLoadingContent(true);
        setContentError(null);

        try {
          const contentResponse = await articleApi.getFeedContentOnTheFly({
            feed_url: feed.link,
          });
          if (contentResponse.content) {
            setFullContent(contentResponse.content);
            articleApi
              .archiveContent(feed.link, feed.title)
              .catch((err) =>
                console.warn("Failed to auto-archive article:", err),
              );
          } else {
            setContentError("Could not fetch article content");
          }
        } catch (error) {
          console.error("Error fetching content:", error);
          setContentError("Could not fetch article content");
        } finally {
          setIsLoadingContent(false);
        }
      }

      setIsContentExpanded((prev) => !prev);
    }, [
      feed.link,
      feed.title,
      fullContent,
      isContentExpanded,
      getCachedContent,
    ]);

    const fetchSummary = useCallback(async () => {
      setIsLoadingSummary(true);
      setSummaryError(null);

      try {
        const summaryResponse = await articleApi.getArticleSummary(feed.link);
        if (
          summaryResponse.matched_articles &&
          summaryResponse.matched_articles.length > 0
        ) {
          setSummary(summaryResponse.matched_articles[0].content);
          setSummaryError(null);
        } else {
          setSummaryError("Could not fetch summary");
        }
      } catch (error) {
        console.error("Error fetching summary:", error);
        setSummaryError("Could not fetch summary");
      } finally {
        setIsLoadingSummary(false);
      }
    }, [feed.link]);

    const handleToggleSummary = useCallback(async () => {
      if (!isSummaryExpanded && !summary) {
        await fetchSummary();
      }

      setIsSummaryExpanded((prev) => !prev);
    }, [feed.link, isSummaryExpanded, summary, fetchSummary]);

    const handleSummarizeNow = useCallback(async () => {
      setIsSummarizing(true);
      setSummaryError(null);

      try {
        const summarizeResponse = await articleApi.summarizeArticle(feed.link);
        console.log("[SwipeFeedCard] Summarize response:", summarizeResponse);

        if (summarizeResponse.success && summarizeResponse.summary) {
          console.log(
            "[SwipeFeedCard] Summary received, length:",
            summarizeResponse.summary.length,
          );
          setSummary(summarizeResponse.summary);
          setSummaryError(null);
        } else {
          console.error(
            "[SwipeFeedCard] Invalid response structure:",
            summarizeResponse,
          );
          setSummaryError("Failed to generate the summary");
        }
      } catch (error) {
        console.error("[SwipeFeedCard] Error summarizing article:", error);
        setSummaryError("Failed to generate the summary");
      } finally {
        setIsSummarizing(false);
      }
    }, [feed.link]);

    const handleDismiss = useCallback(
      async (direction: number) => {
        const normalized = normalizeDirection(direction);

        try {
          // Trigger animation and dismissal in parallel
          // We don't await the animation to finish before calling onDismiss
          // This allows the next card to start rendering immediately
          const animationPromise = playDismissAnimation(normalized);

          // Small delay to ensure animation frame has started
          // This prevents the state update from happening before the transform is applied
          await new Promise((resolve) => setTimeout(resolve, 5));

          await onDismiss(normalized);

          // Ensure animation completes (though component might be unmounted by then)
          await animationPromise;
        } catch (error) {
          resetPosition();
          throw error;
        }
      },
      [onDismiss, playDismissAnimation, resetPosition],
    );

    const bind = useDrag(
      ({ down, movement: [mx], velocity: [vx], direction: [dx], last }) => {
        if (down) {
          api.start({ x: mx, immediate: true });
          return;
        }

        if (last) {
          const shouldDismiss =
            Math.abs(mx) >= SWIPE_DISTANCE || Math.abs(vx) >= SWIPE_VELOCITY;

          if (!shouldDismiss) {
            resetPosition();
            return;
          }

          const direction = dx !== 0 ? dx : Math.sign(mx) || 1;
          void handleDismiss(direction);
        }
      },
      {
        axis: "x",
        filterTaps: true,
        pointer: { touch: true },
      },
    );

    const hasDescription = Boolean(feed.description);
    const publishedLabel = useMemo(() => {
      // Prefer created_at if available, as it's a reliable ISO timestamp
      if (feed.created_at) {
        try {
          return new Date(feed.created_at).toLocaleString();
        } catch {
          // Fallback to published if created_at parsing fails
        }
      }

      if (!feed.published) {
        return null;
      }
      try {
        return new Date(feed.published).toLocaleString();
      } catch {
        return feed.published;
      }
    }, [feed.published, feed.created_at]);

    return (
      <animated.div
        {...bind()}
        style={{
          ...style,
          x,
          touchAction: "none",
          position: "absolute", // Important for stacking during transition
          width: "100%",
          maxWidth: "30rem",
          height: "95dvh",
          background: "var(--alt-glass)",
          color: "var(--alt-text-primary)",
          border: "2px solid var(--alt-glass-border)",
          boxShadow:
            "0 12px 40px rgba(0, 0, 0, 0.3), 0 0 0 1px rgba(255, 255, 255, 0.1)",
          borderRadius: "1rem",
          padding: "1rem",
          backdropFilter: "blur(20px)",
          willChange: "transform, opacity",
          zIndex: style.zIndex, // Apply zIndex from transition
        }}
        data-testid="swipe-card"
        aria-busy={isBusy}
      >
        <VStack align="stretch" gap={0} h="100%">
          <Box
            position="relative"
            zIndex="2"
            bg="rgba(255, 255, 255, 0.03)"
            backdropFilter="blur(20px)"
            borderBottom="1px solid var(--alt-glass-border)"
            px={2}
            py={2}
            borderTopRadius="1rem"
          >
            <Text
              fontSize="sm"
              color="var(--alt-text-secondary)"
              mb={2}
              textTransform="uppercase"
              letterSpacing="0.08em"
              bgGradient="var(--accent-gradient)"
              bgClip="text"
              fontWeight="semibold"
            >
              Swipe to mark as read
            </Text>

            <Flex align="center" gap={2}>
              <Link
                href={feed.link}
                target="_blank"
                rel="noopener noreferrer"
                aria-label="Open article in new tab"
                display="flex"
                alignItems="center"
                justifyContent="center"
                color="var(--alt-text-primary)"
                borderColor="var(--alt-glass-border)"
                border="1px solid"
                borderRadius="md"
                p={2}
                flex="1"
                minWidth={0}
                _hover={{
                  bg: "rgba(255, 255, 255, 0.05)",
                  borderColor: "var(--alt-primary)",
                }}
              >
                <Box flexShrink={0}>
                  <SquareArrowOutUpRight color="var(--alt-primary)" size={20} />
                </Box>
                <Text
                  as="h2"
                  fontSize="xl"
                  fontWeight="bold"
                  flex="1"
                  wordBreak="break-word"
                  whiteSpace="normal"
                  minWidth={0}
                >
                  {feed.title}
                </Text>
              </Link>
            </Flex>

            {publishedLabel && (
              <Text color="var(--alt-text-secondary)" fontSize="sm" mt={2}>
                {publishedLabel}
              </Text>
            )}
          </Box>

          <Box
            flex="1"
            overflow="auto"
            px={2}
            py={2}
            bg="transparent"
            scrollBehavior="smooth"
            overscrollBehavior="contain"
            css={scrollAreaStyles}
            style={{ touchAction: "pan-y" }}
            data-testid="unified-scroll-area"
          >
            {hasDescription && (
              <Box mb={4}>
                <Text
                  fontSize="xs"
                  color="var(--alt-text-secondary)"
                  fontWeight="bold"
                  mb={2}
                  textTransform="uppercase"
                  letterSpacing="1px"
                >
                  Summary
                </Text>
                <Text
                  fontSize="sm"
                  color="var(--alt-text-primary)"
                  lineHeight="1.7"
                >
                  {feed.description}
                </Text>
              </Box>
            )}

            {isContentExpanded && (
              <Box
                mb={4}
                p={4}
                bg="rgba(255, 255, 255, 0.03)"
                borderRadius="12px"
                border="1px solid var(--alt-glass-border)"
                data-testid="content-section"
              >
                <Text
                  fontSize="xs"
                  color="var(--alt-text-secondary)"
                  fontWeight="bold"
                  mb={2}
                  textTransform="uppercase"
                  letterSpacing="1px"
                >
                  Full Article
                </Text>

                {isLoadingContent ? (
                  <HStack justify="center" py={4}>
                    <Spinner size="sm" color="var(--alt-primary)" />
                    <Text color="var(--alt-text-secondary)" fontSize="sm">
                      Loading article content...
                    </Text>
                  </HStack>
                ) : contentError ? (
                  <Text
                    color="var(--alt-text-secondary)"
                    fontSize="sm"
                    textAlign="center"
                  >
                    {contentError}
                  </Text>
                ) : sanitizedFullContent ? (
                  <Box
                    fontSize="sm"
                    color="var(--alt-text-primary)"
                    lineHeight="1.7"
                    css={buildContentStyles()}
                  >
                    {sanitizedFullContent}
                  </Box>
                ) : null}
              </Box>
            )}

            {isSummaryExpanded && (
              <Box
                p={4}
                bg="rgba(255, 255, 255, 0.03)"
                borderRadius="12px"
                border="1px solid var(--alt-glass-border)"
                data-testid="summary-section"
              >
                <Text
                  fontSize="xs"
                  color="var(--alt-text-secondary)"
                  fontWeight="bold"
                  mb={2}
                  textTransform="uppercase"
                  letterSpacing="1px"
                >
                  Summary
                </Text>

                {isLoadingSummary ? (
                  <HStack justify="center" py={4}>
                    <Spinner size="sm" color="var(--alt-primary)" />
                    <Text color="var(--alt-text-secondary)" fontSize="sm">
                      Loading summary...
                    </Text>
                  </HStack>
                ) : isSummarizing ? (
                  <VStack gap={3} py={4}>
                    <HStack justify="center">
                      <Spinner size="sm" color="var(--alt-primary)" />
                      <Text color="var(--alt-text-secondary)" fontSize="sm">
                        Generating summary...
                      </Text>
                    </HStack>
                    <Text
                      color="var(--alt-text-secondary)"
                      fontSize="xs"
                      textAlign="center"
                    >
                      This may take a few seconds
                    </Text>
                  </VStack>
                ) : summaryError ? (
                  <VStack gap={3} w="100%">
                    <Text
                      color="var(--alt-text-secondary)"
                      fontSize="sm"
                      textAlign="center"
                    >
                      {summaryError}
                    </Text>
                    {summaryError === "Could not fetch summary" && (
                      <VStack gap={2} w="100%">
                        <Button
                          size="sm"
                          onClick={fetchSummary}
                          w="100%"
                          borderRadius="12px"
                          bg="var(--alt-primary)"
                          color="white"
                          _hover={{
                            bg: "var(--alt-secondary)",
                            transform: "translateY(-1px)",
                          }}
                          loading={isLoadingSummary}
                          data-testid="retry-summary-button"
                        >
                          <Flex align="center" gap={2}>
                            <Text>Retry</Text>
                          </Flex>
                        </Button>
                        <Button
                          size="sm"
                          onClick={handleSummarizeNow}
                          w="100%"
                          borderRadius="12px"
                          bg="var(--alt-primary)"
                          color="white"
                          _hover={{
                            bg: "var(--alt-secondary)",
                            transform: "translateY(-1px)",
                          }}
                          disabled={isSummarizing}
                          data-testid="summarize-now-button"
                        >
                          <Flex align="center" gap={2}>
                            {isSummarizing ? (
                              <Spinner size="xs" color="white" />
                            ) : (
                              <Sparkles size={16} />
                            )}
                            <Text>
                              {isSummarizing
                                ? "Generating..."
                                : "Summarize Now"}
                            </Text>
                          </Flex>
                        </Button>
                      </VStack>
                    )}
                  </VStack>
                ) : summary ? (
                  <Text
                    fontSize="sm"
                    color="var(--alt-text-primary)"
                    lineHeight="1.7"
                    whiteSpace="pre-wrap"
                  >
                    {summary}
                  </Text>
                ) : (
                  <VStack gap={3} w="100%">
                    {isSummarizing ? (
                      <Flex align="center" justify="center" gap={3} py={2}>
                        <Spinner size="sm" color="var(--alt-primary)" />
                        <Text
                          color="var(--alt-text-secondary)"
                          fontSize="sm"
                          textAlign="center"
                        >
                          Generating summary...
                        </Text>
                      </Flex>
                    ) : (
                      <>
                        <Text
                          color="var(--alt-text-secondary)"
                          fontSize="sm"
                          textAlign="center"
                        >
                          No summary available for this article
                        </Text>
                        <Button
                          size="sm"
                          onClick={handleSummarizeNow}
                          w="100%"
                          borderRadius="12px"
                          bg="var(--alt-primary)"
                          color="white"
                          _hover={{
                            bg: "var(--alt-secondary)",
                            transform: "translateY(-1px)",
                          }}
                          disabled={isSummarizing}
                          data-testid="summarize-now-button"
                        >
                          <Flex align="center" gap={2}>
                            <Sparkles size={16} />
                            <Text>Summarize Now</Text>
                          </Flex>
                        </Button>
                      </>
                    )}
                  </VStack>
                )}
              </Box>
            )}
          </Box>

          <Box
            position="relative"
            zIndex="2"
            bg="rgba(255, 255, 255, 0.05)"
            backdropFilter="blur(20px)"
            borderTop="1px solid var(--alt-glass-border)"
            px={3}
            py={3}
            borderBottomRadius="1rem"
            data-testid="action-footer"
          >
            <HStack gap={2} w="100%" justify="space-between">
              <Button
                onClick={handleToggleContent}
                size="sm"
                flex="1"
                borderRadius="12px"
                bg={
                  isContentExpanded
                    ? "var(--alt-secondary)"
                    : "var(--alt-primary)"
                }
                color="white"
                fontWeight="bold"
                _hover={{
                  filter: "brightness(1.1)",
                  transform: "translateY(-1px)",
                }}
                _active={{
                  transform: "translateY(0)",
                }}
                transition="all 0.2s ease"
                disabled={isLoadingContent}
                data-testid="toggle-content-button"
              >
                <Flex align="center" gap={2}>
                  <BookOpen size={16} />
                  <Text fontSize="xs">
                    {isLoadingContent
                      ? "Loading..."
                      : isContentExpanded
                        ? "Hide"
                        : "Article"}
                  </Text>
                </Flex>
              </Button>

              <Button
                onClick={handleToggleSummary}
                size="sm"
                flex="1"
                borderRadius="12px"
                bg={
                  isSummaryExpanded
                    ? "var(--alt-secondary)"
                    : "var(--alt-primary)"
                }
                color="white"
                fontWeight="bold"
                _hover={{
                  filter: "brightness(1.1)",
                  transform: "translateY(-1px)",
                }}
                _active={{
                  transform: "translateY(0)",
                }}
                transition="all 0.2s ease"
                disabled={isLoadingSummary || isSummarizing}
                data-testid="toggle-summary-button"
              >
                <Flex align="center" gap={2}>
                  {isSummarizing ? (
                    <Spinner size="xs" color="white" />
                  ) : (
                    <BotMessageSquare size={16} />
                  )}
                  <Text fontSize="xs">
                    {isSummarizing
                      ? "Generating..."
                      : isLoadingSummary
                        ? "Loading..."
                        : isSummaryExpanded
                          ? "Hide"
                          : "Summary"}
                  </Text>
                </Flex>
              </Button>

              <Button
                type="button"
                onClick={async () => {
                  if (!feed.link) return;
                  try {
                    setIsArchiving(true);
                    await articleApi.archiveContent(feed.link, feed.title);
                    setIsArchived(true);
                  } catch (e) {
                    console.error("Error archiving feed:", e);
                  } finally {
                    setIsArchiving(false);
                  }
                }}
                size="sm"
                flex="1"
                borderRadius="12px"
                bg="var(--alt-primary)"
                color="var(--text-primary)"
                fontWeight="bold"
                border="1px solid rgba(255, 255, 255, 0.2)"
                _hover={{
                  filter: "brightness(1.1)",
                  transform: "translateY(-1px)",
                }}
                _active={{
                  transform: "translateY(0)",
                }}
                transition="all 0.2s ease"
                disabled={isArchiving || isArchived}
                title="Archive"
                data-testid="archive-button"
              >
                <Flex align="center" gap={1}>
                  <Archive size={14} />
                  <Text fontSize="xs">
                    {isArchiving ? "..." : isArchived ? "✓" : "Archive"}
                  </Text>
                </Flex>
              </Button>
            </HStack>

            {statusMessage && (
              <Text
                fontSize="xs"
                color="var(--alt-text-secondary)"
                textAlign="center"
                mt={2}
              >
                {statusMessage}
              </Text>
            )}
          </Box>
        </VStack>
      </animated.div>
    );
  },
);

const SwipeFeedCard = memo((props: SwipeFeedCardProps) => {
  const transitions = useTransition(props.feed, {
    keys: (item: RenderFeed) => item.id,
    from: { opacity: 0, scale: 0.98, zIndex: 0 },
    enter: { opacity: 1, scale: 1, zIndex: 1 },
    leave: { opacity: 0, pointerEvents: "none", zIndex: 10 },
    config: (_item, state) => {
      if (String(state) === "leave") {
        return { tension: 600, friction: 30 };
      }
      return { tension: 700, friction: 25 };
    },
  });

  return (
    <div style={{ position: "relative", width: "100%", height: "95dvh" }}>
      {transitions((style: any, feed: RenderFeed) => (
        <CardView {...props} feed={feed} style={style} />
      ))}
    </div>
  );
});

SwipeFeedCard.displayName = "SwipeFeedCard";

export default SwipeFeedCard;

// alt-frontend-sv/src/lib/components/mobile/feeds/swipe/SwipeFeedCard.svelte
<script lang="ts">
  import {
    BookOpen,
    Loader,
    Sparkles,
    SquareArrowOutUpRight,
  } from "@lucide/svelte";
  import { onMount, tick } from "svelte";
  import { Spring } from "svelte/motion";
  import { fade } from "svelte/transition";
  import { type SwipeDirection, swipe } from "$lib/actions/swipe";
  import {
    getFeedContentOnTheFlyClient,
    summarizeArticleClient,
    streamSummarizeArticleClient,
  } from "$lib/api/client";
  import { Button } from "$lib/components/ui/button";
  import type { RenderFeed } from "$lib/schema/feed";
  import {
    processStreamingText,
    simulateTypewriterEffect,
  } from "$lib/utils/streamingRenderer";

  interface Props {
    feed: RenderFeed;
    statusMessage: string | null;
    onDismiss: (direction: number) => Promise<void> | void;
    getCachedContent?: (feedUrl: string) => string | null;
    isBusy?: boolean;
    initialArticleContent?: string | null;
  }

  const {
    feed,
    statusMessage,
    onDismiss,
    getCachedContent,
    isBusy = false,
    initialArticleContent,
  }: Props = $props();

  // State
  let isAISummaryRequested = $state(false);
  let aiSummary = $state<string | null>(null);
  let summaryError = $state<string | null>(null);
  let isSummarizing = $state(false);

  let isContentExpanded = $state(false);
  let fullContent = $state<string | null>(null);
  let isLoadingContent = $state(false);
  let contentError = $state<string | null>(null);

  // Swipe state with Spring
  const SWIPE_THRESHOLD = 60;
  const HORIZONTAL_SWIPE_THRESHOLD = 10; // 横スワイプ検出の閾値（px）
  let x = new Spring(0, { stiffness: 0.18, damping: 0.85 });
  let isDragging = $state(false);
  let hasSwiped = $state(false);
  let swipeElement: HTMLDivElement | null = $state(null);
  let scrollAreaRef: HTMLDivElement | null = $state(null);

  // Derived styles
  const cardStyle = $derived.by(() => {
    const translate = x.current;
    const opacity = Math.max(0.4, 1 - Math.abs(translate) / 500);

    return [
      "max-width: calc(100% - 1rem)",
      `transform: translate3d(${translate}px, 0, 0)`,
      `opacity: ${opacity}`,
      "will-change: transform, opacity",
    ].join("; ");
  });

  // Derived
  const sanitizedFullContent = $derived(fullContent);
  const hasDescription = $derived(Boolean(feed.description));
  const publishedLabel = $derived.by(() => {
    if (feed.created_at) {
      try {
        return new Date(feed.created_at).toLocaleString();
      } catch {
        // Fallback
      }
    }
    if (!feed.published) return null;
    try {
      return new Date(feed.published).toLocaleString();
    } catch {
      return feed.published;
    }
  });

  // Auto-fetch content
  onMount(() => {
    // Initialize with prop value if available
    if (initialArticleContent) {
      fullContent = initialArticleContent;
    }

    const cached = getCachedContent?.(feed.link);
    if (cached) {
      fullContent = cached;
    } else if (!fullContent) {
      // Background fetch
      getFeedContentOnTheFlyClient(feed.link)
        .then((res) => {
          if (res.content) {
            fullContent = res.content;
          }
        })
        .catch((err) => {
          console.error("[SwipeFeedCard] Error auto-fetching content:", err);
        });
    }
  });

  // Set up swipe event listeners reactively
  $effect(() => {
    if (!swipeElement) return;

    const swipeHandler = (event: Event) => {
      // 重複処理を防ぐ（scrollAreaRefとswipeElementの両方から発火する可能性がある）
      if (hasSwiped) return;
      handleSwipe(event as CustomEvent<{ direction: SwipeDirection }>);
    };

    const swipeMoveHandler = (event: Event) => {
      const moveEvent = event as CustomEvent<{
        deltaX: number;
        deltaY: number;
      }>;
      const { deltaX, deltaY } = moveEvent.detail;

      // 横方向の動きが優勢なときだけ追従させる
      if (Math.abs(deltaX) > Math.abs(deltaY)) {
        isDragging = true;
        x.set(deltaX, { instant: true });
      }
    };

    const swipeEndHandler = (event: Event) => {
      // ドラッグが終わったので中央に戻す
      // 実際にスワイプが成立した場合は、swipe イベント → handleSwipe → onDismiss が走るので、
      // カード自体はすぐ差し替えられる
      // 成立しなかった場合だけ「中央にスナップバック」という役割分担
      x.target = 0;
      isDragging = false;
    };

    // swipeElementにリスナーを追加
    swipeElement.addEventListener("swipe", swipeHandler);
    swipeElement.addEventListener("swipe:move", swipeMoveHandler);
    swipeElement.addEventListener("swipe:end", swipeEndHandler);

    return () => {
      swipeElement?.removeEventListener("swipe", swipeHandler);
      swipeElement?.removeEventListener("swipe:move", swipeMoveHandler);
      swipeElement?.removeEventListener("swipe:end", swipeEndHandler);
    };
  });

  async function handleToggleContent() {
    if (!isContentExpanded && !fullContent) {
      const cached = getCachedContent?.(feed.link);
      if (cached) {
        fullContent = cached;
        isContentExpanded = true;
        return;
      }

      isLoadingContent = true;
      contentError = null;

      try {
        const res = await getFeedContentOnTheFlyClient(feed.link);
        if (res.content) {
          fullContent = res.content;
        } else {
          contentError = "Could not fetch article content";
        }
      } catch (err) {
        console.error("Error fetching content:", err);
        contentError = "Could not fetch article content";
      } finally {
        isLoadingContent = false;
      }
    }
    isContentExpanded = !isContentExpanded;
  }

  async function handleGenerateAISummary() {
    // Hide existing SUMMARY section
    isAISummaryRequested = true;
    isSummarizing = true;
    summaryError = null;
    aiSummary = "";

    try {
      // Try streaming first
      // We pass fullContent if we have it (e.g. from auto-fetch or expand)
      const reader = await streamSummarizeArticleClient(
        feed.link,
        undefined, // Let backend resolve article_id from URL
        undefined, // Content is fetched from DB by backend
        feed.title,
      );

      // Use streaming renderer utility for incremental rendering
      try {
        const result = await processStreamingText(
          reader,
          (chunk) => {
            aiSummary = (aiSummary || "") + chunk;
          },
          {
            tick,
            typewriter: true, // Enable typewriter effect
            typewriterDelay: 10, // 10ms delay per char
            onChunk: (
              chunkCount,
              chunkSize,
              decodedLength,
              totalLength,
              preview,
            ) => {
              // Hide "Now summarizing..." when first chunk arrives
              if (chunkCount === 1) {
                isSummarizing = false;
              }
              if (chunkCount <= 5) {
                console.log("[StreamSummarize] Chunk received and rendered", {
                  chunkCount,
                  chunkSize,
                  decodedLength,
                  totalLength,
                  preview,
                });
              }
            },
            onComplete: (totalLength, chunkCount) => {
              console.log("[StreamSummarize] Final chunk decoded", {
                chunkCount: chunkCount + 1,
                totalLength,
              });
            },
          },
        );

        const hasReceivedData = result.hasReceivedData;
      } catch (streamErr) {
        // Error during streaming (after initial connection)
        console.error(
          "[StreamSummarize] Error during stream reading:",
          streamErr,
        );
        // If we received some data, keep it and show error
        if (aiSummary && aiSummary.length > 0) {
          console.warn(
            "[StreamSummarize] Stream interrupted but partial data received",
            {
              receivedLength: aiSummary.length,
            },
          );
          summaryError =
            "Stream interrupted. Partial summary may be incomplete.";
        } else {
          // No data received, re-throw to trigger fallback
          throw streamErr;
        }
      }
    } catch (err) {
      const errorMessage = err instanceof Error ? err.message : String(err);
      const isAuthError =
        errorMessage.includes("403") ||
        errorMessage.includes("401") ||
        errorMessage.includes("Forbidden") ||
        errorMessage.includes("Authentication");

      console.error("[StreamSummarize] Error streaming summary:", {
        error: errorMessage,
        isAuthError,
        hasPartialData: !!aiSummary && aiSummary.length > 0,
      });

      // Don't retry on authentication errors - user needs to re-authenticate
      if (isAuthError) {
        summaryError =
          "Authentication failed. Please refresh the page and try again.";
        return;
      }

      // If we have partial data, don't fallback - show what we have
      if (aiSummary && aiSummary.length > 0) {
        console.warn(
          "[StreamSummarize] Using partial summary due to stream error",
        );
        summaryError = "Stream interrupted. Summary may be incomplete.";
        return;
      }

      // Fallback to legacy endpoint only if no data was received
      console.log("[StreamSummarize] Falling back to legacy endpoint");
      try {
        const res = await summarizeArticleClient(feed.link);
        if (res.success && res.summary) {
          // Use typewriter effect for fallback legacy summary too
          isSummarizing = false; // Stop spinner immediately as we have data
          const typewriter = simulateTypewriterEffect(
            (char) => {
              aiSummary = (aiSummary || "") + char;
            },
            { tick, delay: 10 },
          );
          await typewriter.add(res.summary);
        } else {
          isSummarizing = false;
          summaryError = "Failed to generate the summary";
        }
      } catch (legacyErr) {
        console.error(
          "[StreamSummarize] Legacy endpoint also failed:",
          legacyErr,
        );
        isSummarizing = false;
        summaryError = "Failed to generate the summary. Please try again.";
      }
    } finally {
      // If NOT using typewriter effect for fallback, we would set isSummarizing = false here.
      // But for fallback with typewriter, we set it false BEFORE starting typewriter.
      // For streaming with typewriter, processStreamingText handles setting it false on first chunk?
      // Wait, processStreamingText's onChunk callback sets isSummarizing = false.
      // If streaming completes successfully, isSummarizing is already false.
      // If streaming fails and we fallback, we set isSummarizing = false inside fallback block.
      // So we can safely set it false here if it's still true (e.g. total failure).
      if (isSummarizing && aiSummary === "") {
        isSummarizing = false;
      }
      // Note: for successful streaming or fallback-typewriter, isSummarizing becomes false earlier to show text.
    }
  }

  async function handleSwipe(
    event: CustomEvent<{ direction: SwipeDirection }>,
  ) {
    const dir = event.detail.direction;
    if (dir !== "left" && dir !== "right") return;

    hasSwiped = true;
    isDragging = false;

    const width = swipeElement?.clientWidth ?? window.innerWidth;
    const target = dir === "left" ? -width : width;

    // 画面外までスプリングで飛ばす（慣性付きで気持ちよく）
    await x.set(target, { preserveMomentum: 120 });

    // ここで「次の記事へ」「前の記事へ」のロジックを呼ぶ
    await onDismiss(dir === "left" ? -1 : 1);

    // 次のカードに備えてリセット
    hasSwiped = false;
    await x.set(0, { instant: true });
  }
</script>

<div
  bind:this={swipeElement}
  class="absolute w-full h-[95dvh] bg-[var(--alt-glass)] text-[var(--alt-text-primary)] border-2 border-[var(--alt-glass-border)] shadow-[0_12px_40px_rgba(0,0,0,0.3),0_0_0_1px_rgba(255,255,255,0.1)] rounded-2xl p-4 backdrop-blur-[20px] select-none"
  use:swipe={{ threshold: SWIPE_THRESHOLD, restraint: 120, allowedTime: 500 }}
  aria-busy={isBusy}
  data-testid="swipe-card"
  style={`${cardStyle}; touch-action: none;`}
>
  <div class="flex flex-col gap-0 h-full">
    <!-- Header -->
    <div
      class="relative z-[2] bg-[rgba(255,255,255,0.03)] backdrop-blur-[20px] border-b border-[var(--alt-glass-border)] px-2 py-2 rounded-t-2xl"
    >
      <p
        class="text-sm mb-2 uppercase tracking-[0.08em] font-semibold"
        style="color: black;"
      >
        Swipe to mark as read
      </p>
      <div class="flex items-center gap-2">
        <a
          href={feed.link}
          target="_blank"
          rel="noopener noreferrer"
          aria-label="Open article in new tab"
          class="flex items-center justify-center text-[var(--alt-text-primary)] border border-[var(--alt-glass-border)] rounded-md p-2 flex-1 min-w-0 hover:bg-[rgba(255,255,255,0.05)] hover:border-[var(--alt-primary)] transition-colors"
        >
          <div class="shrink-0 mr-2">
            <SquareArrowOutUpRight
              class="text-[var(--alt-primary)]"
              size={20}
            />
          </div>
          <h2
            class="text-xl font-bold flex-1 break-words whitespace-normal min-w-0"
          >
            {feed.title}
          </h2>
        </a>
      </div>
      {#if publishedLabel}
        <p class="text-[var(--alt-text-secondary)] text-sm mt-2">
          {publishedLabel}
        </p>
      {/if}
    </div>

    <!-- Only Vertical Scroll Area -->
    <div
      bind:this={scrollAreaRef}
      style="touch-action: pan-y; overflow-x: hidden;"
      class="flex-1 overflow-y-auto overflow-x-hidden px-2 py-2 bg-transparent scroll-smooth overscroll-contain scrollbar-thin select-none"
      data-testid="unified-scroll-area"
    >
      {#if hasDescription && !isAISummaryRequested}
        <div class="mb-4 overflow-x-hidden" transition:fade>
          <p
            class="text-xs text-[var(--alt-text-secondary)] font-bold mb-2 uppercase tracking-widest"
          >
            Summary
          </p>
          <div
            class="text-sm text-[var(--alt-text-primary)] leading-[1.7] break-words overflow-wrap-anywhere"
          >
            {@html feed.description}
          </div>
        </div>
      {/if}

      {#if isAISummaryRequested}
        <div
          class="px-4 pt-2 pb-4 border-t mb-4 overflow-x-hidden"
          data-testid="ai-summary-section"
          transition:fade
        >
          <p
            class="text-xs text-[var(--alt-text-secondary)] font-semibold mb-2 uppercase tracking-[0.18em]"
          >
            {isSummarizing ? "SUMMARY" : "AI SUMMARY"}
          </p>
          {#if isSummarizing}
            <div class="flex flex-col items-center gap-3 py-4">
              <Loader
                class="animate-spin text-[var(--alt-primary)]"
                size={20}
              />
              <span class="text-[var(--alt-text-secondary)] text-sm"
                >Now summarizing ....</span
              >
            </div>
          {:else if summaryError}
            <p
              class="text-[var(--alt-text-secondary)] text-sm text-center py-4"
            >
              {summaryError}
            </p>
          {:else if aiSummary}
            <p
              class="text-sm text-[var(--alt-text-primary)] leading-relaxed whitespace-pre-wrap break-words overflow-wrap-anywhere"
            >
              {aiSummary}
            </p>
          {/if}
        </div>
      {/if}

      {#if isContentExpanded}
        <div
          class="mb-4 p-4 bg-[rgba(255,255,255,0.03)] rounded-xl border border-[var(--alt-glass-border)] overflow-x-hidden"
          data-testid="content-section"
          transition:fade
        >
          <p
            class="text-xs text-[var(--alt-text-secondary)] font-bold mb-2 uppercase tracking-widest"
          >
            Full Article
          </p>
          {#if isLoadingContent}
            <div class="flex justify-center py-4 gap-2">
              <Loader
                class="animate-spin text-[var(--alt-primary)]"
                size={20}
              />
              <span class="text-[var(--alt-text-secondary)] text-sm"
                >Loading article content...</span
              >
            </div>
          {:else if contentError}
            <p class="text-[var(--alt-text-secondary)] text-sm text-center">
              {contentError}
            </p>
          {:else if sanitizedFullContent}
            <div
              class="text-sm text-[var(--alt-text-primary)] leading-[1.7] prose prose-invert max-w-none break-words overflow-wrap-anywhere overflow-x-hidden"
            >
              {@html sanitizedFullContent}
            </div>
          {/if}
        </div>
      {/if}
    </div>

    <!-- Footer -->
    <div
      class="relative z-[2] bg-[rgba(0,0,0,0.25)] backdrop-blur-[20px] border-t border-[var(--alt-glass-border)] px-3 py-3 rounded-b-2xl shadow-[0_-4px_20px_rgba(0,0,0,0.3)]"
      data-testid="action-footer"
    >
      <div class="flex gap-2 w-full justify-between">
        <Button
          onclick={handleToggleContent}
          size="sm"
          class="flex-1 rounded-xl font-bold text-white hover:brightness-110 active:translate-y-0 transition-all duration-200 shadow-lg {isContentExpanded
            ? 'bg-[slate-200] shadow-[var(--alt-secondary)]/50'
            : 'bg-[slate-200] shadow-[var(--alt-primary)]/50'}"
          disabled={isLoadingContent}
        >
          <BookOpen class="mr-2 h-4 w-4" />
          {isLoadingContent
            ? "Loading..."
            : isContentExpanded
              ? "Hide"
              : "Article"}
        </Button>
        <Button
          onclick={handleGenerateAISummary}
          size="sm"
          class="flex-1 rounded-xl font-bold text-white hover:brightness-110 active:translate-y-0 transition-all duration-200 shadow-lg {isAISummaryRequested
            ? 'bg-[slate-200] shadow-[var(--alt-secondary)]/50'
            : 'bg-[slate-200] shadow-[var(--alt-primary)]/50'}"
          disabled={isSummarizing}
        >
          <Sparkles class="mr-2 h-4 w-4" />
          {isSummarizing
            ? "Summarizing..."
            : isAISummaryRequested
              ? "Summary"
              : "Summary"}
        </Button>
      </div>
    </div>
  </div>
</div>

<style>
  .scrollbar-thin::-webkit-scrollbar {
    width: 4px;
  }
  .scrollbar-thin::-webkit-scrollbar-track {
    background: transparent;
    border-radius: 2px;
  }
  .scrollbar-thin::-webkit-scrollbar-thumb {
    background: rgba(255, 255, 255, 0.2);
    border-radius: 2px;
  }
  .scrollbar-thin::-webkit-scrollbar-thumb:hover {
    background: rgba(255, 255, 255, 0.3);
  }

  /* Androidでテキスト選択がスワイプを妨げないように、親要素とすべての子要素でテキスト選択を無効化 */
  [data-testid="unified-scroll-area"],
  [data-testid="unified-scroll-area"] * {
    -webkit-user-select: none; /* Safari, Chrome */
    -moz-user-select: none; /* Firefox */
    -ms-user-select: none; /* Internet Explorer, Edge */
    user-select: none; /* 標準 */
  }
</style>
