// alt-frontend/src/components/mobile/recap/RecapTimeline.tsx
"use client";

import { Flex } from "@chakra-ui/react";
import RecapCard from "./RecapCard";
import type { RecapGenre } from "@/schema/recap";

type RecapTimelineProps = {
  genres: RecapGenre[];
};

const RecapTimeline = ({ genres }: RecapTimelineProps) => {
  return (
    <Flex direction="column" gap={4} data-testid="recap-timeline">
      {genres.map((genre) => (
        <RecapCard key={genre.genre} genre={genre} />
      ))}
    </Flex>
  );
};

export default RecapTimeline;

// alt-frontend-sv/src/lib/components/mobile/recap/RecapTimeline.svelte
<script lang="ts">
	import type { RecapGenre } from "$lib/schema/recap";
	import RecapCard from "./RecapCard.svelte";

	interface Props {
		genres: RecapGenre[];
	}

	const { genres }: Props = $props();
</script>

<div class="flex flex-col gap-4" data-testid="recap-timeline">
	{#each genres as genre}
		<RecapCard {genre} />
	{/each}
</div>
