// alt-frontend/src/app/mobile/recap/7days/page.tsx
"use client";

import { Box, Flex, Text } from "@chakra-ui/react";
import ErrorState from "@/app/mobile/feeds/_components/ErrorState";
import EmptyFeedState from "@/components/mobile/EmptyFeedState";
import RecapTimeline from "@/components/mobile/recap/RecapTimeline";
import SkeletonFeedCard from "@/components/mobile/SkeletonFeedCard";
import { FloatingMenu } from "@/components/mobile/utils/FloatingMenu";
import { useRecapData } from "@/hooks/useRecapData";

export default function RecapSevenDaysPage() {
  const { data, isInitialLoading, error, retry } = useRecapData();

  // Initial loading skeleton
  if (isInitialLoading) {
    return (
      <Box minH="100dvh" position="relative">
        <Box
          p={5}
          maxW="container.sm"
          mx="auto"
          height="100dvh"
          data-testid="recap-skeleton-container"
        >
          <Flex direction="column" gap={4}>
            {Array.from({ length: 5 }).map((_, index) => (
              <SkeletonFeedCard key={`skeleton-${index}`} />
            ))}
          </Flex>
        </Box>
        <FloatingMenu />
      </Box>
    );
  }

  // Error state
  if (error) {
    return <ErrorState error={error} onRetry={retry} isLoading={false} />;
  }

  // Empty state
  if (!data || data.genres.length === 0) {
    return (
      <Box minH="100dvh" position="relative">
        <EmptyFeedState />
        <FloatingMenu />
      </Box>
    );
  }

  return (
    <Box minH="100dvh" position="relative">
      <Box
        p={5}
        maxW="container.sm"
        mx="auto"
        overflowY="auto"
        overflowX="hidden"
        height="100vh"
        data-testid="recap-scroll-container"
        bg="var(--app-bg)"
      >
        {/* ヘッダー */}
        <Box mb={6}>
          <Text
            fontSize="2xl"
            fontWeight="bold"
            color="var(--accent-primary)"
            mb={2}
            bgGradient="var(--accent-gradient)"
            bgClip="text"
          >
            7 Days Recap
          </Text>
          <Text fontSize="xs" color="var(--text-secondary)">
            Executed: {new Date(data.executedAt).toLocaleString("en-US")}
          </Text>
          <Text fontSize="xs" color="var(--text-secondary)">
            {data.totalArticles.toLocaleString()} articles analyzed
          </Text>
        </Box>

        {/* タイムライン */}
        <RecapTimeline genres={data.genres} />

        {/* フッター余白 */}
        <Box h={20} />
      </Box>

      <FloatingMenu />
    </Box>
  );
}

// alt-frontend-sv/src/routes/mobile/recap/7days/+page.svelte
<script lang="ts">
	import { onMount } from "svelte";
	import { browser } from "$app/environment";
	import { get7DaysRecapClient } from "$lib/api/client";
	import type { RecapSummary } from "$lib/schema/recap";
	import EmptyFeedState from "$lib/components/mobile/EmptyFeedState.svelte";
	import RecapTimeline from "$lib/components/mobile/recap/RecapTimeline.svelte";
	import FloatingMenu from "$lib/components/mobile/feeds/swipe/FloatingMenu.svelte";
	import { Button } from "$lib/components/ui/button";

	let data = $state<RecapSummary | null>(null);
	let isInitialLoading = $state(true);
	let error = $state<Error | null>(null);
	let isRetrying = $state(false);

	const fetchData = async () => {
		try {
			isInitialLoading = true;
			error = null;
			const recap = await get7DaysRecapClient();
			data = recap;
		} catch (err) {
			error = err instanceof Error ? err : new Error("Unknown error");
			data = null;
		} finally {
			isInitialLoading = false;
		}
	};

	const retry = async () => {
		isRetrying = true;
		try {
			await fetchData();
		} catch (err) {
			console.error("Retry failed:", err);
		} finally {
			isRetrying = false;
		}
	};

	onMount(() => {
		if (browser) {
			void fetchData();
		}
	});
</script>

<div class="min-h-[100dvh] relative" style="background: var(--app-bg);">
	{#if isInitialLoading}
		<!-- Initial loading skeleton -->
		<div
			class="p-5 max-w-2xl mx-auto h-[100dvh]"
			data-testid="recap-skeleton-container"
		>
			<div class="flex flex-col gap-4">
				{#each Array(5) as _}
					<div
						class="p-4 rounded-2xl border-2 border-border animate-pulse"
						style="background: var(--surface-bg);"
					>
						<div class="h-4 bg-muted rounded w-3/4 mb-2"></div>
						<div class="h-3 bg-muted rounded w-full mb-1"></div>
						<div class="h-3 bg-muted rounded w-5/6"></div>
					</div>
				{/each}
			</div>
		</div>
	{:else if error}
		<!-- Error state -->
		<div class="flex flex-col items-center justify-center min-h-[50vh] p-6">
			<div
				class="p-6 rounded-lg border text-center"
				style="background: var(--surface-bg); border-color: hsl(var(--destructive));"
			>
				<p
					class="font-semibold mb-2"
					style="color: hsl(var(--destructive));"
				>
					Error loading recap
				</p>
				<p
					class="text-sm mb-4"
					style="color: var(--text-secondary);"
				>
					{error.message}
				</p>
				<Button
					onclick={() => void retry()}
					disabled={isRetrying}
					class="px-4 py-2 rounded disabled:opacity-50"
					style="background: var(--alt-primary); color: var(--text-primary);"
				>
					{isRetrying ? "Retrying..." : "Retry"}
				</Button>
			</div>
		</div>
	{:else if !data || data.genres.length === 0}
		<!-- Empty state -->
		<EmptyFeedState />
	{:else}
		<!-- Content -->
		<div
			class="p-5 max-w-2xl mx-auto overflow-y-auto overflow-x-hidden h-screen"
			data-testid="recap-scroll-container"
			style="background: var(--app-bg);"
		>
			<!-- ヘッダー -->
			<div class="mb-6">
				<h1
					class="text-2xl font-bold mb-2"
					style="color: var(--accent-primary); background: var(--accent-gradient); -webkit-background-clip: text; -webkit-text-fill-color: transparent; background-clip: text;"
				>
					7 Days Recap
				</h1>
				<p
					class="text-xs mb-1"
					style="color: var(--text-secondary);"
				>
					Executed: {new Date(data.executedAt).toLocaleString("en-US")}
				</p>
				<p
					class="text-xs"
					style="color: var(--text-secondary);"
				>
					{data.totalArticles.toLocaleString()} articles analyzed
				</p>
			</div>

			<!-- タイムライン -->
			<RecapTimeline genres={data.genres} />

			<!-- フッター余白 -->
			<div class="h-20"></div>
		</div>
	{/if}

	<FloatingMenu />
</div>
