// alt-frontend-sv/src/lib/components/mobile/FeedCard.svelte
<script lang="ts">
import { SquareArrowOutUpRight } from "@lucide/svelte";
import { Button } from "$lib/components/ui/button";
import type { RenderFeed } from "$lib/schema/feed";
import FeedDetails from "./FeedDetails.svelte";

interface Props {
	feed: RenderFeed;
	isReadStatus: boolean;
	setIsReadStatus: (feedLink: string) => void;
}

const { feed, isReadStatus, setIsReadStatus }: Props = $props();

const handleReadStatus = () => {
	// API呼び出しは親コンポーネントで行うため、コールバックのみ実行
	// normalizedUrlを使用して一貫性を保つ
	setIsReadStatus(feed.normalizedUrl);
};
</script>

{#if !isReadStatus}
	<!-- Gradient border container with hover effects -->
	<div
		class="p-[2px] rounded-[18px] border-2 transition-transform duration-300 ease-in-out cursor-pointer hover:scale-[1.02] hover:shadow-lg"
		style="border-color: var(--surface-border);"
		data-testid="feed-card-container"
	>
		<div
			class="glass w-full p-4 rounded-2xl"
			data-testid="feed-card"
			role="article"
			aria-label="Feed: {feed.title}"
			style="background: var(--surface-bg);"
		>
			<div class="flex flex-col gap-2">
				<!-- Title as link -->
				<div class="flex flex-row items-center gap-2">
					<div
						class="flex items-center justify-center w-6 h-6 flex-shrink-0"
						data-testid="feed-link-icon-{feed.id}"
					>
						<SquareArrowOutUpRight
							size={16}
							style="color: var(--alt-primary);"
						/>
					</div>
					<a
						href={feed.normalizedUrl}
						target="_blank"
						rel="noopener noreferrer"
						aria-label="Open {feed.title} in external link"
						class="text-sm font-semibold hover:underline leading-tight break-words"
						style="color: var(--accent-primary);"
					>
						{feed.title}
					</a>
				</div>

				<!-- Description - Use server-generated excerpt if available -->
				<p
					class="text-xs leading-normal break-words line-clamp-3"
					style="color: var(--text-primary);"
				>
					{feed.excerpt}
				</p>

				<!-- Author name (if available) -->
				{#if feed.author}
					<p class="text-xs italic" style="color: var(--text-secondary);">
						by {feed.author}
					</p>
				{/if}

				<!-- Bottom section with button and details -->
				<div class="flex justify-between items-center mt-3 gap-3">
					<Button
						class="flex-1 text-sm font-bold px-4 min-h-[44px] border border-white/20 rounded-full transition-all duration-200 hover:scale-105 active:scale-95"
						style="
							background: var(--alt-primary);
							color: var(--text-primary);
						"
						onclick={handleReadStatus}
						aria-label="Mark {feed.title} as read"
					>
						Mark as read
					</Button>

					<FeedDetails feedURL={feed.link} feedTitle={feed.title} />
				</div>
			</div>
		</div>
	</div>
{/if}

// alt-frontend/app/src/components/mobile/FeedCard.tsx
import { Button, Flex, Spinner, Text, Box } from "@chakra-ui/react";
import { SanitizedFeed } from "@/schema/feed";
import Link from "next/link";
import { feedsApi } from "@/lib/api";
import { useState, useCallback, memo, KeyboardEvent } from "react";
import { FeedDetails } from "./FeedDetails";
import { truncateFeedDescription } from "@/lib/utils/textUtils";
import { SquareArrowOutUpRight } from "lucide-react";

type FeedCardProps = {
  feed: SanitizedFeed;
  isReadStatus: boolean;
  setIsReadStatus: (isReadStatus: boolean) => void;
};

const FeedCard = memo(function FeedCard({
  feed,
  isReadStatus,
  setIsReadStatus,
}: FeedCardProps) {
  const [isLoading, setIsLoading] = useState(false);

  const handleReadStatus = useCallback(
    async (url: string) => {
      try {
        setIsLoading(true);
        await feedsApi.updateFeedReadStatus(url);
        setIsReadStatus(true);
      } catch (error) {
        console.error("Failed to mark feed as read:", error);
      } finally {
        setIsLoading(false);
      }
    },
    [setIsReadStatus],
  );

  const handleKeyDown = useCallback(
    (event: KeyboardEvent) => {
      if (event.key === "Enter" || event.key === " ") {
        event.preventDefault();
        handleReadStatus(feed.link);
      }
    },
    [feed.link, handleReadStatus],
  );

  // Don't render if already read
  if (isReadStatus) {
    return null;
  }

  // Truncate description for better UX
  const truncatedDescription = truncateFeedDescription(feed.description);

  return (
    // Gradient border container with hover effects
    <Box
      p="2px"
      borderRadius="18px"
      /* Use solid border instead of gradient */
      border="2px solid var(--surface-border)"
      transition="transform 0.3s ease-in-out, box-shadow 0.3s ease-in-out"
      cursor="pointer"
      data-testid="feed-card-container"
    >
      <Box
        className="glass"
        w="full"
        p={5}
        borderRadius="16px"
        data-testid="feed-card"
        role="article"
        tabIndex={0}
        onKeyDown={handleKeyDown}
        aria-label={`Feed: ${feed.title}`}
        bg="var(--surface-bg)"
      >
        <Flex direction="column" gap={2}>
          {/* Title as link */}
          <Flex direction="row" align="center" gap={2}>
            <Box
              display="flex"
              alignItems="center"
              justifyContent="center"
              width="24px"
              height="24px"
              flexShrink={0}
              data-testid={`feed-link-icon-${feed.id}`}
            >
              <SquareArrowOutUpRight color="var(--alt-primary)" size={24} />
            </Box>
            <Link
              href={feed.link}
              target="_blank"
              rel="noopener noreferrer"
              aria-label={`Open ${feed.title} in external link`}
            >
              <Text
                fontSize="md"
                fontWeight="semibold"
                color="var(--accent-primary)"
                _hover={{ textDecoration: "underline" }}
                lineHeight="1.4"
              >
                {feed.title}
              </Text>
            </Link>
          </Flex>

          {/* Description */}
          <Text fontSize="sm" color="var(--text-primary)" lineHeight="1.5">
            {truncatedDescription}
          </Text>

          {/* Author name (if available) */}
          {feed.author && (
            <Text
              fontSize="xs"
              color="var(--text-secondary)"
              fontStyle="italic"
            >
              by {feed.author}
            </Text>
          )}

          {/* Bottom section with button and details */}
          <Flex justify="space-between" align="center" mt={2}>
            <Button
              size="sm"
              borderRadius="full"
              bg="var(--alt-primary)"
              color="var(--text-primary)"
              fontWeight="bold"
              px={4}
              minHeight="44px"
              minWidth="120px"
              fontSize="sm"
              border="1px solid rgba(255, 255, 255, 0.2)"
              disabled={isLoading}
              onClick={() => handleReadStatus(feed.link)}
              _hover={{
                bg: "var(--accent-gradient)",
                transform: "scale(1.05)",
                boxShadow: "0 4px 12px var(--accent-primary)",
              }}
              _active={{
                transform: "scale(0.98)",
              }}
              _disabled={{
                opacity: 0.6,
                cursor: "not-allowed",
              }}
              transition="all 0.2s ease"
              aria-label={`Mark ${feed.title} as read`}
            >
              {isLoading ? <Spinner size="sm" /> : "Mark as read"}
            </Button>

            <FeedDetails feedURL={feed.link} />
          </Flex>
        </Flex>
      </Box>
    </Box>
  );
});

export default FeedCard;
