// alt-frontend/app/src/components/mobile/search/SearchWindow.tsx
import { useState } from "react";
import { Box, Button, Input, Text, VStack } from "@chakra-ui/react";
import {
  SearchQuery,
  searchQuerySchema,
} from "@/schema/validation/searchQuery";
import { feedsApi } from "@/lib/api";
import type { BackendFeedItem } from "@/schema/feed";
import { transformFeedSearchResult } from "@/lib/utils/transformFeedSearchResult";
import * as v from "valibot";

interface SearchWindowProps {
  searchQuery: SearchQuery;
  setSearchQuery: (query: SearchQuery) => void;
  feedResults: BackendFeedItem[];
  setFeedResults: (results: BackendFeedItem[]) => void;
  isLoading: boolean;
  setIsLoading: (loading: boolean) => void;
  setSearchTime?: (time: number) => void;
}

const SearchWindow = ({
  searchQuery,
  setSearchQuery,
  setFeedResults,
  isLoading,
  setIsLoading,
  setSearchTime,
}: SearchWindowProps) => {
  const [error, setError] = useState<string | null>(null);
  const [validationError, setValidationError] = useState<string | null>(null);

  // Real-time validation
  const validateQuery = (query: SearchQuery) => {
    const validationResult = v.safeParse(searchQuerySchema, query);
    if (!validationResult.success) {
      const firstError = validationResult.issues?.[0]?.message || "Please enter a valid search query";
      setValidationError(firstError);
      return false;
    }
    setValidationError(null);
    return true;
  };

  const handleSearch = async () => {
    if (isLoading) return;

    const startTime = Date.now();
    setIsLoading(true);
    setError(null);
    setValidationError(null);

    try {
      // 1. Clear previous results
      setFeedResults([]);

      // 2. Validate input
      const validationResult = v.safeParse(searchQuerySchema, searchQuery);

      if (!validationResult.success) {
        const firstError = validationResult.issues?.[0]?.message || "Please enter a valid search query";
        setValidationError(firstError);
        return;
      }

      const validatedQuery = validationResult.output.query;

      // 3. Call API
      const results = await feedsApi.searchFeeds(validatedQuery);

      if (results.error) {
        setError(results.error);
        return;
      }

      // 4. Transform results
      const transformedResults = transformFeedSearchResult(results);

      // 5. Pass results to parent via prop function
      setFeedResults(transformedResults);

      // 6. Track search time
      const searchTime = Date.now() - startTime;
      setSearchTime?.(searchTime);

    } catch (err) {
      console.error("Search error:", err);
      setError(err instanceof Error ? err.message : "Search failed. Please try again.");
    } finally {
      setIsLoading(false);
    }
  };

  const handleFormSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    handleSearch();
  };

  const handleKeyPress = (e: React.KeyboardEvent) => {
    if (e.key === 'Enter') {
      e.preventDefault();
      handleSearch();
    }
  };

  return (
    <Box data-testid="search-window">
      <form onSubmit={handleFormSubmit}>
        <VStack gap={4}>
          <Box width="full">
            <Text
              color="rgba(255, 255, 255, 0.9)"
              mb={2}
              fontSize="sm"
              fontWeight="medium"
            >
              Search Query
            </Text>
            <Input
              data-testid="search-input"
              type="text"
              placeholder="Search for feeds..."
              value={searchQuery.query || ""}
              onChange={(e: React.ChangeEvent<HTMLInputElement>) => {
                const newQuery = { query: e.target.value };
                setSearchQuery(newQuery);
                // Clear errors when user starts typing
                if (error) setError(null);
                // Real-time validation for better UX
                if (e.target.value.trim()) {
                  validateQuery(newQuery);
                } else {
                  setValidationError(null);
                }
              }}
              onKeyDown={handleKeyPress}
              bg="rgba(255, 255, 255, 0.1)"
              border={`1px solid ${validationError ? "#f87171" : "rgba(255, 255, 255, 0.2)"}`}
              color="white"
              _placeholder={{ color: "rgba(255, 255, 255, 0.5)" }}
              _focus={{
                borderColor: validationError ? "#f87171" : "#ff006e",
                boxShadow: `0 0 0 1px ${validationError ? "#f87171" : "#ff006e"}`,
              }}
            />
          </Box>

          <Button
            type="submit"
            loading={isLoading}
            bg="linear-gradient(45deg, #ff006e, #8338ec)"
            color="white"
            fontWeight="bold"
            px={8}
            py={6}
            borderRadius="full"
            _hover={{
              bg: "linear-gradient(45deg, #e6005c, #7129d4)",
              transform: "translateY(-2px)",
            }}
            _active={{
              transform: "translateY(0px)",
            }}
            transition="all 0.2s ease"
            border="1px solid rgba(255, 255, 255, 0.2)"
            width="full"
            disabled={isLoading || !!validationError}
            opacity={validationError ? 0.6 : 1}
          >
            {isLoading ? "Searching..." : "Search"}
          </Button>

          {validationError && (
            <Text
              color="#f87171"
              textAlign="center"
              fontSize="sm"
              fontWeight="medium"
            >
              {validationError}
            </Text>
          )}

          {error && (
            <Text
              color="#f87171"
              textAlign="center"
              fontSize="sm"
              fontWeight="medium"
            >
              {error}
            </Text>
          )}
        </VStack>
      </form>
    </Box>
  );
};

export default SearchWindow;

// alt-frontend-sv/src/lib/components/mobile/search/SearchWindow.svelte
<script lang="ts">
import * as v from "valibot";
import { searchFeedsClient } from "$lib/api/client";
import { transformFeedSearchResult } from "$lib/utils/transformFeedSearchResult";
import type { SearchFeedItem, SearchQuery } from "$lib/schema/search";
import { Button } from "$lib/components/ui/button";
import { Input } from "$lib/components/ui/input";
import { Loader } from "@lucide/svelte";

interface Props {
	searchQuery: SearchQuery;
	setSearchQuery: (query: SearchQuery) => void;
	setFeedResults: (results: SearchFeedItem[]) => void;
	setCursor: (cursor: string | null) => void;
	setHasMore: (hasMore: boolean) => void;
	isLoading: boolean;
	setIsLoading: (loading: boolean) => void;
	setSearchTime?: (time: number) => void;
}

const {
	searchQuery,
	setSearchQuery,
	setFeedResults,
	setCursor,
	setHasMore,
	isLoading,
	setIsLoading,
	setSearchTime,
}: Props = $props();

let error = $state<string | null>(null);
let validationError = $state<string | null>(null);
let abortController: AbortController | null = $state(null);

// Search query schema for validation
const searchQuerySchema = v.object({
	query: v.pipe(
		v.string("Please enter a search query"),
		v.trim(),
		v.nonEmpty("Please enter a search query"),
		v.minLength(2, "Search query must be at least 2 characters"),
		v.maxLength(100, "Search query must be at most 100 characters"),
	),
});

// Validate query function
function validateQuery(queryText: string): string | null {
	const trimmed = queryText.trim();

	if (!trimmed) {
		return "Please enter a search query";
	}

	if (trimmed.length < 2) {
		return "Search query must be at least 2 characters";
	}

	const result = v.safeParse(searchQuerySchema, { query: trimmed });
	if (!result.success) {
		return result.issues?.[0]?.message || "Please enter a valid search query";
	}

	return null;
}

const handleSearch = async () => {
	if (isLoading) return;

	// Cancel any in-flight request
	if (abortController) {
		abortController.abort();
	}

	abortController = new AbortController();

	const startTime = Date.now();
	setIsLoading(true);
	error = null;
	validationError = null;

	try {
		// 1. Clear previous results
		setFeedResults([]);
		setCursor(null);
		setHasMore(false);

		// 2. Validate input
		const validationResult = validateQuery(searchQuery.query || "");

		if (validationResult) {
			validationError = validationResult;
			setIsLoading(false);
			return;
		}

		const validatedQuery = searchQuery.query.trim();

		// 3. Call API
		const searchResult = await searchFeedsClient(validatedQuery);

		// Check if aborted
		if (abortController?.signal.aborted) {
			setIsLoading(false);
			return;
		}

		if (searchResult.error) {
			error = searchResult.error;
			setIsLoading(false);
			return;
		}

		// 4. Transform results
		const transformedResults = transformFeedSearchResult(searchResult);

		// 5. Update state
		setFeedResults(transformedResults);
		// Convert cursor to string for state management (offset as string)
		setCursor(
			searchResult.next_cursor !== null &&
				searchResult.next_cursor !== undefined
				? String(searchResult.next_cursor)
				: null,
		);
		// Use next_cursor to determine hasMore (same pattern as ViewedFeedsClient)
		setHasMore(searchResult.next_cursor !== null);

		// 6. Track search time
		const searchTime = Date.now() - startTime;
		setSearchTime?.(searchTime);
	} catch (err) {
		if (abortController?.signal.aborted) {
			setIsLoading(false);
			return; // Ignore abort errors
		}
		console.error("Search error:", err);
		error =
			err instanceof Error ? err.message : "Search failed. Please try again.";
	} finally {
		// Always reset loading state if not aborted
		if (!abortController?.signal.aborted) {
			setIsLoading(false);
		}
	}
};

const handleFormSubmit = (e: Event) => {
	e.preventDefault();
	// Always validate on form submit
	const validationResult = validateQuery(searchQuery.query || "");
	if (validationResult) {
		validationError = validationResult;
		return;
	}
	// Only proceed with search if validation passes
	handleSearch();
};

const handleKeyPress = (e: KeyboardEvent) => {
	if (e.key === "Enter") {
		e.preventDefault();
		// Directly call the form submission logic
		const validationResult = validateQuery(searchQuery.query || "");

		if (validationResult) {
			validationError = validationResult;
			return;
		}

		// Only proceed with search if validation passes
		handleSearch();
	}
};

const handleInputChange = (e: Event) => {
	const target = e.target as HTMLInputElement;
	const newQuery = target.value;
	setSearchQuery({ query: newQuery });

	// Clear API errors when user starts typing
	if (error) error = null;

	// Clear validation error when user types enough characters
	if (newQuery.trim().length >= 2) {
		validationError = null;
	}
};
</script>

<div data-testid="search-window">
	<form onsubmit={handleFormSubmit}>
		<div class="flex flex-col gap-4">
			<div class="w-full">
				<label
					for="search-input"
					class="block mb-2 text-sm font-medium"
					style="color: var(--text-secondary);"
				>
					Search Query
				</label>
				<Input
					id="search-input"
					data-testid="search-input"
					type="text"
					value={searchQuery.query || ""}
					oninput={handleInputChange}
					onkeydown={handleKeyPress}
					placeholder="e.g. AI, technology, startup..."
					disabled={isLoading}
					class={validationError
						? "border-[#dc2626] focus-visible:border-[#dc2626]"
						: ""}
				/>
			</div>

			<Button
				type="submit"
				class="w-full rounded-full min-h-[48px] font-semibold text-base transition-all duration-200 hover:scale-[1.02] active:scale-[0.98] disabled:opacity-60"
				style="
					background: var(--alt-primary);
					color: black;
				"
				disabled={isLoading || !!validationError}
			>
				{#if isLoading}
					<div class="flex items-center gap-2">
						<Loader class="h-4 w-4 animate-spin" />
						<span>Searching...</span>
					</div>
				{:else}
					Search
				{/if}
			</Button>

			{#if validationError}
				<p
					class="text-center text-sm font-medium"
					style="color: #dc2626;"
				>
					{validationError}
				</p>
			{/if}

			{#if error}
				<p
					class="text-center text-sm font-medium"
					style="color: #dc2626;"
				>
					{error}
				</p>
			{/if}
		</div>
	</form>
</div>
