// alt-frontend/src/components/mobile/search/SearchFeedsClient.tsx
"use client";

import { Box, Text, VStack } from "@chakra-ui/react";
import { Suspense, useState, useTransition, useDeferredValue } from "react";
import dynamic from "next/dynamic";
import { FloatingMenu } from "@/components/mobile/utils/FloatingMenu";
import type { SearchFeedItem } from "@/schema/search";
import type { SearchQuery } from "@/schema/validation/searchQuery";

// Dynamic imports with loading states
const SearchWindow = dynamic(
  () => import("@/components/mobile/search/SearchWindow"),
  {
    loading: () => (
      <Box
        bg="var(--bg-glass)"
        backdropFilter="blur(12px)"
        p={6}
        borderRadius="24px"
        border="1px solid var(--border-glass)"
        boxShadow="var(--shadow-glass)"
      >
        <Box
          height="48px"
          bg="var(--bg-surface)"
          borderRadius="12px"
          opacity={0.6}
        />
      </Box>
    ),
    ssr: false,
  },
);

const SearchResults = dynamic(
  () => import("@/components/mobile/search/SearchResults"),
  {
    loading: () => null,
    ssr: false,
  },
);

export default function SearchFeedsClient() {
  const [searchQuery, setSearchQuery] = useState<SearchQuery>({ query: "" });
  const [results, setResults] = useState<SearchFeedItem[]>([]);
  const [isLoading, setIsLoading] = useState(false);
  const [searchTime, setSearchTime] = useState<number>();
  const [isPending, _startTransition] = useTransition();

  // Defer search query updates to reduce validation overhead
  const deferredQuery = useDeferredValue(searchQuery);

  return (
    <Box minHeight="100dvh" bg="var(--app-bg)" color="var(--foreground)" p={4}>
      <VStack gap={6} align="stretch" maxWidth="600px" mx="auto">
        {/* Header Section */}
        <VStack gap={3} mt={4} mb={2}>
          <Text
            fontSize="2xl"
            fontWeight="700"
            textAlign="center"
            color="var(--text-primary)"
            letterSpacing="-0.025em"
          >
            Search Feeds
          </Text>
          <Text
            textAlign="center"
            color="var(--text-secondary)"
            fontSize="md"
            maxWidth="400px"
            lineHeight="1.7"
          >
            Discover content across your RSS feeds with intelligent search
          </Text>
        </VStack>

        {/* Search Input Section */}
        <Box
          bg="var(--bg-glass)"
          backdropFilter="blur(12px)"
          p={6}
          borderRadius="24px"
          border="1px solid var(--border-glass)"
          boxShadow="var(--shadow-glass)"
        >
          <Suspense
            fallback={
              <Box
                height="48px"
                bg="var(--bg-surface)"
                borderRadius="12px"
                opacity={0.6}
              />
            }
          >
            <SearchWindow
              searchQuery={searchQuery}
              setSearchQuery={setSearchQuery}
              feedResults={results}
              setFeedResults={setResults}
              isLoading={isLoading || isPending}
              setIsLoading={setIsLoading}
              setSearchTime={setSearchTime}
            />
          </Suspense>
        </Box>

        {/* Search Results Section */}
        <Suspense fallback={null}>
          <SearchResults
            results={results}
            isLoading={isLoading || isPending}
            searchQuery={deferredQuery.query || ""}
            searchTime={searchTime}
          />
        </Suspense>

        {/* Quick Tips */}
        {!searchQuery.query && !isLoading && results.length === 0 && (
          <Box
            bg="var(--bg-glass)"
            backdropFilter="blur(12px)"
            p={4}
            borderRadius="24px"
            border="1px solid var(--border-glass)"
            boxShadow="var(--shadow-glass)"
          >
            <Text
              color="var(--text-secondary)"
              fontSize="sm"
              textAlign="center"
              lineHeight="1.7"
            >
              💡 Try searching for topics like &quot;AI&quot;,
              &quot;technology&quot;, or &quot;news&quot;
            </Text>
          </Box>
        )}
      </VStack>

      <FloatingMenu />
    </Box>
  );
}

// alt-frontend-sv/src/lib/components/mobile/search/SearchFeedsClient.svelte
<script lang="ts">
import { onMount } from "svelte";
import { browser } from "$app/environment";
import type { SearchFeedItem, SearchQuery } from "$lib/schema/search";
import SearchWindow from "./SearchWindow.svelte";
import SearchResults from "./SearchResults.svelte";
import FloatingMenu from "../feeds/swipe/FloatingMenu.svelte";

let searchQuery = $state<SearchQuery>({ query: "" });
let results = $state<SearchFeedItem[]>([]);
let isLoading = $state(false);
let searchTime = $state<number | undefined>(undefined);
let cursor = $state<string | null>(null);
let hasMore = $state(false);

// Ensure we start at the top on mount
onMount(() => {
	if (browser && window.scrollTo) {
		window.scrollTo(0, 0);
	}
});
</script>

<div
	class="min-h-screen p-4"
	style="background: var(--app-bg); color: var(--foreground);"
>
	<div class="flex flex-col gap-6 max-w-[600px] mx-auto">
		<!-- Header Section -->
		<div class="flex flex-col gap-3 mt-2 mb-2">
			<h1
				class="text-2xl font-bold text-center tracking-tight"
				style="color: var(--text-primary);"
			>
				Search Feeds
			</h1>
			<p
				class="text-center text-base max-w-[400px] mx-auto leading-relaxed"
				style="color: var(--text-secondary);"
			>
				Discover content across your RSS feeds with intelligent search
			</p>
		</div>

		<!-- Search Input Section -->
		<div
			class="glass p-2 rounded-[24px]"
			style="
				background: var(--alt-glass);
				border: 1px solid var(--alt-glass-border);
				box-shadow: var(--alt-glass-shadow);
			"
		>
			<SearchWindow
				{searchQuery}
				setSearchQuery={(query) => {
					searchQuery = query;
				}}
				setFeedResults={(newResults) => {
					results = newResults;
				}}
				setCursor={(newCursor) => {
					cursor = newCursor;
				}}
				setHasMore={(newHasMore) => {
					hasMore = newHasMore;
				}}
				{isLoading}
				setIsLoading={(loading) => {
					isLoading = loading;
				}}
				setSearchTime={(time) => {
					searchTime = time;
				}}
			/>
		</div>

		<!-- Search Results Section -->
		<SearchResults
			{results}
			{isLoading}
			searchQuery={searchQuery.query || ""}
			{searchTime}
			{cursor}
			{hasMore}
			setResults={(newResults) => {
				results = newResults;
			}}
			setCursor={(newCursor) => {
				cursor = newCursor;
			}}
			setHasMore={(newHasMore) => {
				hasMore = newHasMore;
			}}
			setIsLoading={(loading) => {
				isLoading = loading;
			}}
		/>

		<!-- Quick Tips -->
		{#if !searchQuery.query && !isLoading && results.length === 0}
			<div
				class="glass p-4 rounded-[24px]"
				style="
					background: var(--alt-glass);
					border: 1px solid var(--alt-glass-border);
					box-shadow: var(--alt-glass-shadow);
				"
			>
				<p
					class="text-sm text-center leading-relaxed"
					style="color: var(--text-secondary);"
				>
					💡 Try searching for topics like &quot;AI&quot;,
					&quot;technology&quot;, or &quot;news&quot;
				</p>
			</div>
		{/if}
	</div>

	<FloatingMenu />
</div>
