// alt-frontend/src/components/desktop/home/PageHeader.tsx
import type React from "react";

interface PageHeaderProps {
  title: string;
  description: string;
}

export const PageHeader: React.FC<PageHeaderProps> = ({
  title,
  description,
}) => {
  return (
    <div role="banner" className="py-6">
      <h1 className="text-3xl font-bold text-gray-900 mb-4">{title}</h1>
      <p className="text-lg text-gray-600">{description}</p>
    </div>
  );
};

// alt-frontend-sv/src/lib/components/desktop/layout/PageHeader.svelte
<script lang="ts">
	let { title, description = "" }: { title: string; description?: string } = $props();
</script>

<header class="mb-6">
	<h1 class="text-2xl font-bold text-[var(--text-primary)]">{title}</h1>
	{#if description}
		<p class="text-sm text-[var(--text-secondary)] mt-1">{description}</p>
	{/if}
</header>
